// Code generated by sorm gen. DO NOT EDIT.

package sormgen

import (
	"context"

	"github.com/dvislobokov/sorm"

	models "github.com/dvislobokov/sorm/examples/webapp/models"
)

// Context is the unit-of-work facade: a sorm.Session plus a typed set
// per entity. Queries via sets are tracked (identity map + snapshots);
// mutate entities with plain Go code and call SaveChanges.
// Not thread-safe — create one per request or transaction.
type Context struct {
	*sorm.Session

	Tasks sorm.Set[models.Task]
	Users sorm.Set[models.User]
}

// NewContext starts a unit of work over db (a pool or an open transaction).
func NewContext(db sorm.DB) *Context {
	s := sorm.NewSession(db)
	return &Context{
		Session: s,
		Tasks:   sorm.NewSet[models.Task](s),
		Users:   sorm.NewSet[models.User](s),
	}
}

// RunInTx runs fn in a transaction: commit on nil, rollback on error,
// retries on transient failures (serialization, deadlock). Each attempt
// gets a FRESH child context bound to the transaction — work only
// through it inside fn; the parent context's state is not visible and
// must not be mixed in. SaveChanges on the child flushes into this
// transaction without opening a nested one.
func (c *Context) RunInTx(ctx context.Context, fn func(txc *Context) error) error {
	return sorm.RunInTx(ctx, c.Session.DB(), func(tx sorm.Tx) error {
		return fn(NewContext(tx))
	})
}
