// Code generated by sorm gen. DO NOT EDIT.

package sormgen

import (
	"time"

	"sorm"

	models "sorm/examples/webapp/models"
)

// Task — типизированные дескрипторы колонок models.Task.
var Task = struct {
	ID        sorm.OrdCol[models.Task, int64]
	UserID    sorm.OrdCol[models.Task, int64]
	Title     sorm.StrCol[models.Task]
	Done      sorm.Col[models.Task, bool]
	Priority  sorm.OrdCol[models.Task, int]
	CreatedAt sorm.OrdCol[models.Task, time.Time]
	Version   sorm.OrdCol[models.Task, int64]
	User      sorm.BelongsTo[models.Task, models.User]
}{
	ID:        sorm.NewOrdCol[models.Task, int64]("tasks", "id"),
	UserID:    sorm.NewOrdCol[models.Task, int64]("tasks", "user_id"),
	Title:     sorm.NewStrCol[models.Task]("tasks", "title"),
	Done:      sorm.NewCol[models.Task, bool]("tasks", "done"),
	Priority:  sorm.NewOrdCol[models.Task, int]("tasks", "priority"),
	CreatedAt: sorm.NewOrdCol[models.Task, time.Time]("tasks", "created_at"),
	Version:   sorm.NewOrdCol[models.Task, int64]("tasks", "version"),
	User: sorm.NewBelongsTo[models.Task, models.User](
		"user_id",
		func(c *models.Task) any { return c.UserID },
		func(c *models.Task, p *models.User) { c.User = p },
	),
}

type taskSnap struct {
	fUserID    int64
	fTitle     string
	fDone      bool
	fPriority  int
	fCreatedAt time.Time
}

func init() {
	sorm.Register(taskMeta)
	sorm.RegisterTable(taskTableDef)
}

var taskTableDef = sorm.TableDef{
	Name: "tasks",
	Columns: []sorm.ColumnDef{
		{Name: "id", GoKind: "int64", PK: true, Auto: true},
		{Name: "user_id", GoKind: "int64", RefTable: "users", RefCol: "id"},
		{Name: "title", GoKind: "string"},
		{Name: "done", GoKind: "bool"},
		{Name: "priority", GoKind: "int"},
		{Name: "created_at", GoKind: "time"},
		{Name: "version", GoKind: "int64"},
	},
}

var taskMeta = sorm.Meta[models.Task]{
	Table:      "tasks",
	PK:         "id",
	Auto:       true,
	VersionCol: "version",
	SelectCols: []string{"id", "user_id", "title", "done", "priority", "created_at", "version"},
	InsertCols: []string{"user_id", "title", "done", "priority", "created_at", "version"},
	Scan: func(e *models.Task) []any {
		return []any{&e.ID, &e.UserID, &e.Title, &e.Done, &e.Priority, &e.CreatedAt, &e.Version}
	},
	InsertValues: func(e *models.Task) []any {
		return []any{e.UserID, e.Title, e.Done, e.Priority, e.CreatedAt, e.Version}
	},
	ValuesFor: func(e *models.Task, cols []int) []any {
		out := make([]any, len(cols))
		for i, c := range cols {
			switch c {
			case 0:
				out[i] = e.ID
			case 1:
				out[i] = e.UserID
			case 2:
				out[i] = e.Title
			case 3:
				out[i] = e.Done
			case 4:
				out[i] = e.Priority
			case 5:
				out[i] = e.CreatedAt
			case 6:
				out[i] = e.Version
			}
		}
		return out
	},
	Snapshot: func(e *models.Task) any {
		return taskSnap{
			fUserID:    e.UserID,
			fTitle:     e.Title,
			fDone:      e.Done,
			fPriority:  e.Priority,
			fCreatedAt: e.CreatedAt.Round(0),
		}
	},
	Diff: func(s any, e *models.Task) []int {
		snap := s.(taskSnap)
		var ch []int
		if snap.fUserID != e.UserID {
			ch = append(ch, 1)
		}
		if snap.fTitle != e.Title {
			ch = append(ch, 2)
		}
		if snap.fDone != e.Done {
			ch = append(ch, 3)
		}
		if snap.fPriority != e.Priority {
			ch = append(ch, 4)
		}
		if !snap.fCreatedAt.Equal(e.CreatedAt) {
			ch = append(ch, 5)
		}
		return ch
	},
	SetPK:      func(e *models.Task, id int64) { e.ID = id },
	PKValue:    func(e *models.Task) any { return e.ID },
	GetVersion: func(e *models.Task) int64 { return e.Version },
	SetVersion: func(e *models.Task, v int64) { e.Version = v },
	Refs: []sorm.Ref[models.Task]{
		{
			FKCol:   "user_id",
			NotNull: true,
			Nav: func(e *models.Task) any {
				if e.User == nil {
					return nil
				}
				return e.User
			},
			NavPK:    func(e *models.Task) any { return e.User.ID },
			SetFK:    func(e *models.Task, pk any) { e.UserID = pk.(int64) },
			FKIsZero: func(e *models.Task) bool { return e.UserID == 0 },
		},
	},
	RefTables: []string{"users"},
}
