// Code generated by sorm gen. DO NOT EDIT.

package sormgen

import (
	"sorm"

	models "sorm/examples/webapp/models"
)

// User — типизированные дескрипторы колонок models.User.
var User = struct {
	ID      sorm.OrdCol[models.User, int64]
	Name    sorm.StrCol[models.User]
	Email   sorm.StrCol[models.User]
	Version sorm.OrdCol[models.User, int64]
	Tasks   sorm.HasMany[models.User, models.Task]
}{
	ID:      sorm.NewOrdCol[models.User, int64]("users", "id"),
	Name:    sorm.NewStrCol[models.User]("users", "name"),
	Email:   sorm.NewStrCol[models.User]("users", "email"),
	Version: sorm.NewOrdCol[models.User, int64]("users", "version"),
	Tasks: sorm.NewHasMany[models.User, models.Task](
		"user_id",
		func(e *models.User) any { return e.ID },
		func(c *models.Task) any { return c.UserID },
		func(e *models.User) { e.Tasks = []*models.Task{} },
		func(e *models.User, c *models.Task) { e.Tasks = append(e.Tasks, c) },
	),
}

type userSnap struct {
	fName  string
	fEmail string
}

func init() {
	sorm.Register(userMeta)
	sorm.RegisterTable(userTableDef)
}

var userTableDef = sorm.TableDef{
	Name: "users",
	Columns: []sorm.ColumnDef{
		{Name: "id", GoKind: "int64", PK: true, Auto: true},
		{Name: "name", GoKind: "string"},
		{Name: "email", GoKind: "string", Unique: true},
		{Name: "version", GoKind: "int64"},
	},
}

var userMeta = sorm.Meta[models.User]{
	Table:      "users",
	PK:         "id",
	Auto:       true,
	VersionCol: "version",
	SelectCols: []string{"id", "name", "email", "version"},
	InsertCols: []string{"name", "email", "version"},
	Scan: func(e *models.User) []any {
		return []any{&e.ID, &e.Name, &e.Email, &e.Version}
	},
	InsertValues: func(e *models.User) []any {
		return []any{e.Name, e.Email, e.Version}
	},
	ValuesFor: func(e *models.User, cols []int) []any {
		out := make([]any, len(cols))
		for i, c := range cols {
			switch c {
			case 0:
				out[i] = e.ID
			case 1:
				out[i] = e.Name
			case 2:
				out[i] = e.Email
			case 3:
				out[i] = e.Version
			}
		}
		return out
	},
	Snapshot: func(e *models.User) any {
		return userSnap{
			fName:  e.Name,
			fEmail: e.Email,
		}
	},
	Diff: func(s any, e *models.User) []int {
		snap := s.(userSnap)
		var ch []int
		if snap.fName != e.Name {
			ch = append(ch, 1)
		}
		if snap.fEmail != e.Email {
			ch = append(ch, 2)
		}
		return ch
	},
	SetPK:      func(e *models.User, id int64) { e.ID = id },
	PKValue:    func(e *models.User) any { return e.ID },
	GetVersion: func(e *models.User) int64 { return e.Version },
	SetVersion: func(e *models.User, v int64) { e.Version = v },
}
