// Code generated by sorm gen. DO NOT EDIT.

package sormgen

import (
	"github.com/dvislobokov/sorm"

	models "github.com/dvislobokov/sorm/internal/testmodels"
)

// ApiKey — типизированные дескрипторы колонок models.ApiKey.
var ApiKey = struct {
	ID     sorm.StrCol[models.ApiKey]
	UserID sorm.OrdCol[models.ApiKey, int64]
	Label  sorm.StrCol[models.ApiKey]
	User   sorm.BelongsTo[models.ApiKey, models.User]
}{
	ID:     sorm.NewStrCol[models.ApiKey]("api_keys", "id"),
	UserID: sorm.NewOrdCol[models.ApiKey, int64]("api_keys", "user_id"),
	Label:  sorm.NewStrCol[models.ApiKey]("api_keys", "label"),
	User: sorm.NewBelongsTo[models.ApiKey, models.User](
		"user_id",
		func(c *models.ApiKey) any { return c.UserID },
		func(c *models.ApiKey, p *models.User) { c.User = p },
	),
}

type apiKeySnap struct {
	fUserID int64
	fLabel  string
}

func init() {
	sorm.Register(apiKeyMeta)
	sorm.RegisterTable(apiKeyTableDef)
}

var apiKeyTableDef = sorm.TableDef{
	Name: "api_keys",
	Columns: []sorm.ColumnDef{
		{Name: "id", GoKind: "string", PK: true, SQLType: "varchar(36)"},
		{Name: "user_id", GoKind: "int64", RefTable: "users", RefCol: "id"},
		{Name: "label", GoKind: "string"},
	},
}

var apiKeyMeta = sorm.Meta[models.ApiKey]{
	Table:      "api_keys",
	PK:         "id",
	SelectCols: []string{"id", "user_id", "label"},
	InsertCols: []string{"id", "user_id", "label"},
	Scan: func(e *models.ApiKey) []any {
		return []any{&e.ID, &e.UserID, &e.Label}
	},
	InsertValues: func(e *models.ApiKey) []any {
		return []any{e.ID, e.UserID, e.Label}
	},
	ValuesFor: func(e *models.ApiKey, cols []int) []any {
		out := make([]any, len(cols))
		for i, c := range cols {
			switch c {
			case 0:
				out[i] = e.ID
			case 1:
				out[i] = e.UserID
			case 2:
				out[i] = e.Label
			}
		}
		return out
	},
	Snapshot: func(e *models.ApiKey) any {
		return apiKeySnap{
			fUserID: e.UserID,
			fLabel:  e.Label,
		}
	},
	Diff: func(s any, e *models.ApiKey) []int {
		snap := s.(apiKeySnap)
		var ch []int
		if snap.fUserID != e.UserID {
			ch = append(ch, 1)
		}
		if snap.fLabel != e.Label {
			ch = append(ch, 2)
		}
		return ch
	},
	PKValue: func(e *models.ApiKey) any { return e.ID },
	Refs: []sorm.Ref[models.ApiKey]{
		{
			FKCol:   "user_id",
			NotNull: true,
			Nav: func(e *models.ApiKey) any {
				if e.User == nil {
					return nil
				}
				return e.User
			},
			NavPK:    func(e *models.ApiKey) any { return e.User.ID },
			SetFK:    func(e *models.ApiKey, pk any) { e.UserID = pk.(int64) },
			FKIsZero: func(e *models.ApiKey) bool { return e.UserID == 0 },
		},
	},
	RefTables: []string{"users"},
}
