// Code generated by sorm gen. DO NOT EDIT.

package sormgen

import (
	"github.com/dvislobokov/sorm"

	models "github.com/dvislobokov/sorm/internal/testmodels"
)

// Comment holds typed column descriptors for models.Comment.
var Comment = struct {
	ID     sorm.OrdCol[models.Comment, int64]
	PostID sorm.OrdCol[models.Comment, int64]
	Body   sorm.StrCol[models.Comment]
	Post   sorm.BelongsTo[models.Comment, models.Post]
}{
	ID:     sorm.NewOrdCol[models.Comment, int64]("comments", "id"),
	PostID: sorm.NewOrdCol[models.Comment, int64]("comments", "post_id"),
	Body:   sorm.NewStrCol[models.Comment]("comments", "body"),
	Post: sorm.NewBelongsTo[models.Comment, models.Post](
		"post_id",
		func(c *models.Comment) any {
			if c.PostID == nil {
				return nil
			}
			return *c.PostID
		},
		func(c *models.Comment, p *models.Post) { c.Post = p },
	),
}

type commentSnap struct {
	fPostID *int64
	fBody   string
}

func init() {
	sorm.Register(commentMeta)
	sorm.RegisterTable(commentTableDef)
}

var commentTableDef = sorm.TableDef{
	Name: "comments",
	Columns: []sorm.ColumnDef{
		{Name: "id", GoKind: "int64", PK: true, Auto: true},
		{Name: "post_id", GoKind: "int64", Nullable: true, RefTable: "posts", RefCol: "id"},
		{Name: "body", GoKind: "string"},
	},
}

var commentMeta = sorm.Meta[models.Comment]{
	Table:      "comments",
	PK:         "id",
	Auto:       true,
	SelectCols: []string{"id", "post_id", "body"},
	InsertCols: []string{"post_id", "body"},
	Scan: func(e *models.Comment) []any {
		return []any{&e.ID, &e.PostID, &e.Body}
	},
	InsertValues: func(e *models.Comment) []any {
		return []any{e.PostID, e.Body}
	},
	ValuesFor: func(e *models.Comment, cols []int) []any {
		out := make([]any, len(cols))
		for i, c := range cols {
			switch c {
			case 0:
				out[i] = e.ID
			case 1:
				out[i] = e.PostID
			case 2:
				out[i] = e.Body
			}
		}
		return out
	},
	Snapshot: func(e *models.Comment) any {
		return commentSnap{
			fPostID: sorm.ClonePtr(e.PostID),
			fBody:   e.Body,
		}
	},
	Diff: func(s any, e *models.Comment) []int {
		snap := s.(commentSnap)
		var ch []int
		if !sorm.PtrEq(snap.fPostID, e.PostID) {
			ch = append(ch, 1)
		}
		if snap.fBody != e.Body {
			ch = append(ch, 2)
		}
		return ch
	},
	SetPK:   func(e *models.Comment, id int64) { e.ID = id },
	PKValue: func(e *models.Comment) any { return e.ID },
	Refs: []sorm.Ref[models.Comment]{
		{
			FKCol:   "post_id",
			NotNull: false,
			Nav: func(e *models.Comment) any {
				if e.Post == nil {
					return nil
				}
				return e.Post
			},
			NavPK:    func(e *models.Comment) any { return e.Post.ID },
			SetFK:    func(e *models.Comment, pk any) { v := pk.(int64); e.PostID = &v },
			FKIsZero: func(e *models.Comment) bool { return e.PostID == nil },
		},
	},
	RefTables: []string{"posts"},
}
