// Code generated by sorm gen. DO NOT EDIT.

package sormgen

import (
	"github.com/dvislobokov/sorm"
	"github.com/google/uuid"

	models "github.com/dvislobokov/sorm/internal/testmodels"
)

// Device holds typed column descriptors for models.Device.
var Device = struct {
	ID      sorm.Col[models.Device, uuid.UUID]
	OwnerID sorm.OrdCol[models.Device, int64]
	Token   sorm.Col[models.Device, uuid.UUID]
	Name    sorm.StrCol[models.Device]
	Owner   sorm.BelongsTo[models.Device, models.User]
}{
	ID:      sorm.NewCol[models.Device, uuid.UUID]("devices", "id"),
	OwnerID: sorm.NewOrdCol[models.Device, int64]("devices", "owner_id"),
	Token:   sorm.NewCol[models.Device, uuid.UUID]("devices", "token"),
	Name:    sorm.NewStrCol[models.Device]("devices", "name"),
	Owner: sorm.NewBelongsTo[models.Device, models.User](
		"owner_id",
		func(c *models.Device) any { return c.OwnerID },
		func(c *models.Device, p *models.User) { c.Owner = p },
	),
}

type deviceSnap struct {
	fOwnerID int64
	fToken   *uuid.UUID
	fName    string
}

func init() {
	sorm.Register(deviceMeta)
	sorm.RegisterTable(deviceTableDef)
}

var deviceTableDef = sorm.TableDef{
	Name: "devices",
	Columns: []sorm.ColumnDef{
		{Name: "id", GoKind: "uuid", PK: true},
		{Name: "owner_id", GoKind: "int64", RefTable: "users", RefCol: "id"},
		{Name: "token", GoKind: "uuid", Nullable: true},
		{Name: "name", GoKind: "string"},
	},
}

var deviceMeta = sorm.Meta[models.Device]{
	Table:      "devices",
	PK:         "id",
	SelectCols: []string{"id", "owner_id", "token", "name"},
	InsertCols: []string{"id", "owner_id", "token", "name"},
	Scan: func(e *models.Device) []any {
		return []any{&e.ID, &e.OwnerID, &e.Token, &e.Name}
	},
	InsertValues: func(e *models.Device) []any {
		return []any{e.ID, e.OwnerID, e.Token, e.Name}
	},
	ValuesFor: func(e *models.Device, cols []int) []any {
		out := make([]any, len(cols))
		for i, c := range cols {
			switch c {
			case 0:
				out[i] = e.ID
			case 1:
				out[i] = e.OwnerID
			case 2:
				out[i] = e.Token
			case 3:
				out[i] = e.Name
			}
		}
		return out
	},
	Snapshot: func(e *models.Device) any {
		return deviceSnap{
			fOwnerID: e.OwnerID,
			fToken:   sorm.ClonePtr(e.Token),
			fName:    e.Name,
		}
	},
	Diff: func(s any, e *models.Device) []int {
		snap := s.(deviceSnap)
		var ch []int
		if snap.fOwnerID != e.OwnerID {
			ch = append(ch, 1)
		}
		if !sorm.PtrEq(snap.fToken, e.Token) {
			ch = append(ch, 2)
		}
		if snap.fName != e.Name {
			ch = append(ch, 3)
		}
		return ch
	},
	PKValue: func(e *models.Device) any { return e.ID },
	Refs: []sorm.Ref[models.Device]{
		{
			FKCol:   "owner_id",
			NotNull: true,
			Nav: func(e *models.Device) any {
				if e.Owner == nil {
					return nil
				}
				return e.Owner
			},
			NavPK:    func(e *models.Device) any { return e.Owner.ID },
			SetFK:    func(e *models.Device, pk any) { e.OwnerID = pk.(int64) },
			FKIsZero: func(e *models.Device) bool { return e.OwnerID == 0 },
		},
	},
	RefTables: []string{"users"},
}
