// Code generated by sorm gen. DO NOT EDIT.

package sormgen

import "github.com/dvislobokov/sorm"

func init() {
	sorm.RegisterTable(sorm.TableDef{
		Name: "user_tags",
		Columns: []sorm.ColumnDef{
			{Name: "user_id", GoKind: "int64", PK: true, RefTable: "users", RefCol: "id"},
			{Name: "tag_id", GoKind: "int64", PK: true, RefTable: "tags", RefCol: "id"},
		},
	})
}
