// Code generated by sorm gen. DO NOT EDIT.

package sormgen

import (
	"sorm"

	models "sorm/internal/testmodels"
)

// Post — типизированные дескрипторы колонок models.Post.
var Post = struct {
	ID       sorm.OrdCol[models.Post, int64]
	AuthorID sorm.OrdCol[models.Post, int64]
	Title    sorm.StrCol[models.Post]
	Body     sorm.StrCol[models.Post]
	Author   sorm.BelongsTo[models.Post, models.User]
}{
	ID:       sorm.NewOrdCol[models.Post, int64]("posts", "id"),
	AuthorID: sorm.NewOrdCol[models.Post, int64]("posts", "author_id"),
	Title:    sorm.NewStrCol[models.Post]("posts", "title"),
	Body:     sorm.NewStrCol[models.Post]("posts", "body"),
	Author: sorm.NewBelongsTo[models.Post, models.User](
		"author_id",
		func(c *models.Post) any { return c.AuthorID },
		func(c *models.Post, p *models.User) { c.Author = p },
	),
}

type postSnap struct {
	fAuthorID int64
	fTitle    string
	fBody     string
}

func init() {
	sorm.Register(postMeta)
	sorm.RegisterTable(postTableDef)
}

var postTableDef = sorm.TableDef{
	Name: "posts",
	Columns: []sorm.ColumnDef{
		{Name: "id", GoKind: "int64", PK: true, Auto: true},
		{Name: "author_id", GoKind: "int64", RefTable: "users", RefCol: "id"},
		{Name: "title", GoKind: "string"},
		{Name: "body", GoKind: "string"},
	},
}

var postMeta = sorm.Meta[models.Post]{
	Table:      "posts",
	PK:         "id",
	Auto:       true,
	SelectCols: []string{"id", "author_id", "title", "body"},
	InsertCols: []string{"author_id", "title", "body"},
	Scan: func(e *models.Post) []any {
		return []any{&e.ID, &e.AuthorID, &e.Title, &e.Body}
	},
	InsertValues: func(e *models.Post) []any {
		return []any{e.AuthorID, e.Title, e.Body}
	},
	ValuesFor: func(e *models.Post, cols []int) []any {
		out := make([]any, len(cols))
		for i, c := range cols {
			switch c {
			case 0:
				out[i] = e.ID
			case 1:
				out[i] = e.AuthorID
			case 2:
				out[i] = e.Title
			case 3:
				out[i] = e.Body
			}
		}
		return out
	},
	Snapshot: func(e *models.Post) any {
		return postSnap{
			fAuthorID: e.AuthorID,
			fTitle:    e.Title,
			fBody:     e.Body,
		}
	},
	Diff: func(s any, e *models.Post) []int {
		snap := s.(postSnap)
		var ch []int
		if snap.fAuthorID != e.AuthorID {
			ch = append(ch, 1)
		}
		if snap.fTitle != e.Title {
			ch = append(ch, 2)
		}
		if snap.fBody != e.Body {
			ch = append(ch, 3)
		}
		return ch
	},
	SetPK:   func(e *models.Post, id int64) { e.ID = id },
	PKValue: func(e *models.Post) any { return e.ID },
	Refs: []sorm.Ref[models.Post]{
		{
			FKCol:   "author_id",
			NotNull: true,
			Nav: func(e *models.Post) any {
				if e.Author == nil {
					return nil
				}
				return e.Author
			},
			NavPK:    func(e *models.Post) any { return e.Author.ID },
			SetFK:    func(e *models.Post, pk any) { e.AuthorID = pk.(int64) },
			FKIsZero: func(e *models.Post) bool { return e.AuthorID == 0 },
		},
	},
	RefTables: []string{"users"},
}
