// Code generated by sorm gen. DO NOT EDIT.

package sormgen

import (
	"bytes"

	"github.com/dvislobokov/sorm"

	models "github.com/dvislobokov/sorm/internal/testmodels"
)

// Profile holds typed column descriptors for models.Profile.
var Profile = struct {
	ID       sorm.OrdCol[models.Profile, int64]
	UserID   sorm.OrdCol[models.Profile, int64]
	Bio      sorm.StrCol[models.Profile]
	Prefs    sorm.JSONCol[models.Profile]
	PrefsDoc struct {
		Theme  sorm.JSONStr[models.Profile]
		Limit  sorm.JSONNum[models.Profile, int64]
		Beta   sorm.JSONBool[models.Profile]
		Labels sorm.JSONArr[models.Profile]
		Notify struct {
			Email sorm.JSONBool[models.Profile]
			Chan  sorm.JSONStr[models.Profile]
		}
	}
	Meta sorm.JSONCol[models.Profile]
}{
	ID:     sorm.NewOrdCol[models.Profile, int64]("profiles", "id"),
	UserID: sorm.NewOrdCol[models.Profile, int64]("profiles", "user_id"),
	Bio:    sorm.NewStrCol[models.Profile]("profiles", "bio"),
	Prefs:  sorm.NewJSONCol[models.Profile]("profiles", "prefs"),
	PrefsDoc: struct {
		Theme  sorm.JSONStr[models.Profile]
		Limit  sorm.JSONNum[models.Profile, int64]
		Beta   sorm.JSONBool[models.Profile]
		Labels sorm.JSONArr[models.Profile]
		Notify struct {
			Email sorm.JSONBool[models.Profile]
			Chan  sorm.JSONStr[models.Profile]
		}
	}{
		Theme:  sorm.NewJSONStr[models.Profile]("profiles", "prefs", "theme"),
		Limit:  sorm.NewJSONNum[models.Profile, int64]("profiles", "prefs", "limit"),
		Beta:   sorm.NewJSONBool[models.Profile]("profiles", "prefs", "beta"),
		Labels: sorm.NewJSONArr[models.Profile]("profiles", "prefs", "labels"),
		Notify: struct {
			Email sorm.JSONBool[models.Profile]
			Chan  sorm.JSONStr[models.Profile]
		}{
			Email: sorm.NewJSONBool[models.Profile]("profiles", "prefs", "notify.email"),
			Chan:  sorm.NewJSONStr[models.Profile]("profiles", "prefs", "notify.chan"),
		},
	},
	Meta: sorm.NewJSONCol[models.Profile]("profiles", "meta"),
}

type profileSnap struct {
	fUserID int64
	fBio    string
	fPrefs  []byte
	fMeta   []byte
}

func init() {
	sorm.Register(profileMeta)
	sorm.RegisterTable(profileTableDef)
}

var profileTableDef = sorm.TableDef{
	Name: "profiles",
	Columns: []sorm.ColumnDef{
		{Name: "id", GoKind: "int64", PK: true, Auto: true},
		{Name: "user_id", GoKind: "int64", RefTable: "users", RefCol: "id"},
		{Name: "bio", GoKind: "string"},
		{Name: "prefs", GoKind: "json", Nullable: true},
		{Name: "meta", GoKind: "json", Nullable: true},
	},
	Indexes: []sorm.IndexDef{
		{Name: "uq_profiles_user", Columns: []string{"user_id"}, Unique: true},
	},
}

var profileMeta = sorm.Meta[models.Profile]{
	Table:      "profiles",
	PK:         "id",
	Auto:       true,
	SelectCols: []string{"id", "user_id", "bio", "prefs", "meta"},
	InsertCols: []string{"user_id", "bio", "prefs", "meta"},
	Scan: func(e *models.Profile) []any {
		return []any{&e.ID, &e.UserID, &e.Bio, sorm.JSONScan(&e.Prefs), sorm.JSONScan(&e.Meta)}
	},
	InsertValues: func(e *models.Profile) []any {
		return []any{e.UserID, e.Bio, sorm.JSONValue(e.Prefs), sorm.JSONValue(e.Meta)}
	},
	ValuesFor: func(e *models.Profile, cols []int) []any {
		out := make([]any, len(cols))
		for i, c := range cols {
			switch c {
			case 0:
				out[i] = e.ID
			case 1:
				out[i] = e.UserID
			case 2:
				out[i] = e.Bio
			case 3:
				out[i] = sorm.JSONValue(e.Prefs)
			case 4:
				out[i] = sorm.JSONValue(e.Meta)
			}
		}
		return out
	},
	Snapshot: func(e *models.Profile) any {
		return profileSnap{
			fUserID: e.UserID,
			fBio:    e.Bio,
			fPrefs:  sorm.JSONSnapshot(e.Prefs),
			fMeta:   sorm.JSONSnapshot(e.Meta),
		}
	},
	Diff: func(s any, e *models.Profile) []int {
		snap := s.(profileSnap)
		var ch []int
		if snap.fUserID != e.UserID {
			ch = append(ch, 1)
		}
		if snap.fBio != e.Bio {
			ch = append(ch, 2)
		}
		if !bytes.Equal(snap.fPrefs, sorm.JSONSnapshot(e.Prefs)) {
			ch = append(ch, 3)
		}
		if !bytes.Equal(snap.fMeta, sorm.JSONSnapshot(e.Meta)) {
			ch = append(ch, 4)
		}
		return ch
	},
	SetPK:   func(e *models.Profile, id int64) { e.ID = id },
	PKValue: func(e *models.Profile) any { return e.ID },
}
