// Code generated by sorm gen. DO NOT EDIT.

package sormgen

import (
	"sorm"

	models "sorm/internal/testmodels"
)

// Profile — типизированные дескрипторы колонок models.Profile.
var Profile = struct {
	ID     sorm.OrdCol[models.Profile, int64]
	UserID sorm.OrdCol[models.Profile, int64]
	Bio    sorm.StrCol[models.Profile]
}{
	ID:     sorm.NewOrdCol[models.Profile, int64]("profiles", "id"),
	UserID: sorm.NewOrdCol[models.Profile, int64]("profiles", "user_id"),
	Bio:    sorm.NewStrCol[models.Profile]("profiles", "bio"),
}

type profileSnap struct {
	fUserID int64
	fBio    string
}

func init() {
	sorm.Register(profileMeta)
	sorm.RegisterTable(profileTableDef)
}

var profileTableDef = sorm.TableDef{
	Name: "profiles",
	Columns: []sorm.ColumnDef{
		{Name: "id", GoKind: "int64", PK: true, Auto: true},
		{Name: "user_id", GoKind: "int64", RefTable: "users", RefCol: "id"},
		{Name: "bio", GoKind: "string"},
	},
	Indexes: []sorm.IndexDef{
		{Name: "uq_profiles_user", Columns: []string{"user_id"}, Unique: true},
	},
}

var profileMeta = sorm.Meta[models.Profile]{
	Table:      "profiles",
	PK:         "id",
	Auto:       true,
	SelectCols: []string{"id", "user_id", "bio"},
	InsertCols: []string{"user_id", "bio"},
	Scan: func(e *models.Profile) []any {
		return []any{&e.ID, &e.UserID, &e.Bio}
	},
	InsertValues: func(e *models.Profile) []any {
		return []any{e.UserID, e.Bio}
	},
	ValuesFor: func(e *models.Profile, cols []int) []any {
		out := make([]any, len(cols))
		for i, c := range cols {
			switch c {
			case 0:
				out[i] = e.ID
			case 1:
				out[i] = e.UserID
			case 2:
				out[i] = e.Bio
			}
		}
		return out
	},
	Snapshot: func(e *models.Profile) any {
		return profileSnap{
			fUserID: e.UserID,
			fBio:    e.Bio,
		}
	},
	Diff: func(s any, e *models.Profile) []int {
		snap := s.(profileSnap)
		var ch []int
		if snap.fUserID != e.UserID {
			ch = append(ch, 1)
		}
		if snap.fBio != e.Bio {
			ch = append(ch, 2)
		}
		return ch
	},
	SetPK:   func(e *models.Profile, id int64) { e.ID = id },
	PKValue: func(e *models.Profile) any { return e.ID },
}
