// Code generated by sorm gen. DO NOT EDIT.

package sormgen

import (
	"sorm"

	models "sorm/internal/testmodels"
)

// Tag — типизированные дескрипторы колонок models.Tag.
var Tag = struct {
	ID    sorm.OrdCol[models.Tag, int64]
	Label sorm.StrCol[models.Tag]
}{
	ID:    sorm.NewOrdCol[models.Tag, int64]("tags", "id"),
	Label: sorm.NewStrCol[models.Tag]("tags", "label"),
}

type tagSnap struct {
	fLabel string
}

func init() {
	sorm.Register(tagMeta)
	sorm.RegisterTable(tagTableDef)
}

var tagTableDef = sorm.TableDef{
	Name: "tags",
	Columns: []sorm.ColumnDef{
		{Name: "id", GoKind: "int64", PK: true, Auto: true},
		{Name: "label", GoKind: "string", Unique: true},
	},
}

var tagMeta = sorm.Meta[models.Tag]{
	Table:      "tags",
	PK:         "id",
	Auto:       true,
	SelectCols: []string{"id", "label"},
	InsertCols: []string{"label"},
	Scan: func(e *models.Tag) []any {
		return []any{&e.ID, &e.Label}
	},
	InsertValues: func(e *models.Tag) []any {
		return []any{e.Label}
	},
	ValuesFor: func(e *models.Tag, cols []int) []any {
		out := make([]any, len(cols))
		for i, c := range cols {
			switch c {
			case 0:
				out[i] = e.ID
			case 1:
				out[i] = e.Label
			}
		}
		return out
	},
	Snapshot: func(e *models.Tag) any {
		return tagSnap{
			fLabel: e.Label,
		}
	},
	Diff: func(s any, e *models.Tag) []int {
		snap := s.(tagSnap)
		var ch []int
		if snap.fLabel != e.Label {
			ch = append(ch, 1)
		}
		return ch
	},
	SetPK:   func(e *models.Tag, id int64) { e.ID = id },
	PKValue: func(e *models.Tag) any { return e.ID },
}
