// Code generated by sorm gen. DO NOT EDIT.

package sormgen

import (
	"bytes"
	"slices"
	"time"

	"github.com/dvislobokov/sorm"

	models "github.com/dvislobokov/sorm/internal/testmodels"
)

// User holds typed column descriptors for models.User.
var User = struct {
	ID        sorm.OrdCol[models.User, int64]
	Email     sorm.StrCol[models.User]
	Name      sorm.StrCol[models.User]
	Nickname  sorm.StrCol[models.User]
	Active    sorm.Col[models.User, bool]
	Age       sorm.OrdCol[models.User, int]
	Balance   sorm.OrdCol[models.User, float64]
	Avatar    sorm.BytesCol[models.User]
	CreatedAt sorm.OrdCol[models.User, time.Time]
	DeletedAt sorm.OrdCol[models.User, time.Time]
	Version   sorm.OrdCol[models.User, int64]
	Posts     sorm.HasMany[models.User, models.Post]
	Tags      sorm.ManyToMany[models.User, models.Tag]
	Profile   sorm.HasOne[models.User, models.Profile]
}{
	ID:        sorm.NewOrdCol[models.User, int64]("users", "id"),
	Email:     sorm.NewStrCol[models.User]("users", "email"),
	Name:      sorm.NewStrCol[models.User]("users", "name"),
	Nickname:  sorm.NewStrCol[models.User]("users", "nickname"),
	Active:    sorm.NewCol[models.User, bool]("users", "active"),
	Age:       sorm.NewOrdCol[models.User, int]("users", "age"),
	Balance:   sorm.NewOrdCol[models.User, float64]("users", "balance"),
	Avatar:    sorm.NewBytesCol[models.User]("users", "avatar"),
	CreatedAt: sorm.NewOrdCol[models.User, time.Time]("users", "created_at"),
	DeletedAt: sorm.NewOrdCol[models.User, time.Time]("users", "deleted_at"),
	Version:   sorm.NewOrdCol[models.User, int64]("users", "version"),
	Posts: sorm.NewHasMany[models.User, models.Post](
		"author_id",
		func(e *models.User) any { return e.ID },
		func(c *models.Post) any { return c.AuthorID },
		func(e *models.User) { e.Posts = []*models.Post{} },
		func(e *models.User, c *models.Post) { e.Posts = append(e.Posts, c) },
	),
	Tags: sorm.NewManyToMany[models.User, models.Tag](
		"user_tags", "user_id", "tag_id",
		func(e *models.User) { e.Tags = []*models.Tag{} },
		func(e *models.User, c *models.Tag) { e.Tags = append(e.Tags, c) },
	),
	Profile: sorm.NewHasOne[models.User, models.Profile](
		"user_id",
		func(e *models.User) any { return e.ID },
		func(c *models.Profile) any { return c.UserID },
		func(e *models.User, c *models.Profile) { e.Profile = c },
	),
}

type userSnap struct {
	fEmail     string
	fName      string
	fNickname  *string
	fActive    bool
	fAge       int
	fBalance   float64
	fAvatar    []byte
	fCreatedAt time.Time
	fDeletedAt *time.Time
}

func init() {
	sorm.Register(userMeta)
	sorm.RegisterTable(userTableDef)
}

var userTableDef = sorm.TableDef{
	Name: "users",
	Columns: []sorm.ColumnDef{
		{Name: "id", GoKind: "int64", PK: true, Auto: true},
		{Name: "email", GoKind: "string", Unique: true},
		{Name: "name", GoKind: "string"},
		{Name: "nickname", GoKind: "string", Nullable: true},
		{Name: "active", GoKind: "bool"},
		{Name: "age", GoKind: "int"},
		{Name: "balance", GoKind: "float64"},
		{Name: "avatar", GoKind: "bytes", Nullable: true},
		{Name: "created_at", GoKind: "time"},
		{Name: "deleted_at", GoKind: "time", Nullable: true},
		{Name: "version", GoKind: "int64"},
	},
	Indexes: append([]sorm.IndexDef{}, models.User{}.Indexes()...),
}

var userMeta = sorm.Meta[models.User]{
	Table:      "users",
	PK:         "id",
	Auto:       true,
	VersionCol: "version",
	SelectCols: []string{"id", "email", "name", "nickname", "active", "age", "balance", "avatar", "created_at", "deleted_at", "version"},
	InsertCols: []string{"email", "name", "nickname", "active", "age", "balance", "avatar", "created_at", "deleted_at", "version"},
	Scan: func(e *models.User) []any {
		return []any{&e.ID, &e.Email, &e.Name, &e.Nickname, &e.Active, &e.Age, &e.Balance, &e.Avatar, &e.CreatedAt, &e.DeletedAt, &e.Version}
	},
	InsertValues: func(e *models.User) []any {
		return []any{e.Email, e.Name, e.Nickname, e.Active, e.Age, e.Balance, e.Avatar, e.CreatedAt, e.DeletedAt, e.Version}
	},
	ValuesFor: func(e *models.User, cols []int) []any {
		out := make([]any, len(cols))
		for i, c := range cols {
			switch c {
			case 0:
				out[i] = e.ID
			case 1:
				out[i] = e.Email
			case 2:
				out[i] = e.Name
			case 3:
				out[i] = e.Nickname
			case 4:
				out[i] = e.Active
			case 5:
				out[i] = e.Age
			case 6:
				out[i] = e.Balance
			case 7:
				out[i] = e.Avatar
			case 8:
				out[i] = e.CreatedAt
			case 9:
				out[i] = e.DeletedAt
			case 10:
				out[i] = e.Version
			}
		}
		return out
	},
	Snapshot: func(e *models.User) any {
		return userSnap{
			fEmail:     e.Email,
			fName:      e.Name,
			fNickname:  sorm.ClonePtr(e.Nickname),
			fActive:    e.Active,
			fAge:       e.Age,
			fBalance:   e.Balance,
			fAvatar:    slices.Clone(e.Avatar),
			fCreatedAt: e.CreatedAt.Round(0),
			fDeletedAt: sorm.CloneTimePtr(e.DeletedAt),
		}
	},
	Diff: func(s any, e *models.User) []int {
		snap := s.(userSnap)
		var ch []int
		if snap.fEmail != e.Email {
			ch = append(ch, 1)
		}
		if snap.fName != e.Name {
			ch = append(ch, 2)
		}
		if !sorm.PtrEq(snap.fNickname, e.Nickname) {
			ch = append(ch, 3)
		}
		if snap.fActive != e.Active {
			ch = append(ch, 4)
		}
		if snap.fAge != e.Age {
			ch = append(ch, 5)
		}
		if snap.fBalance != e.Balance {
			ch = append(ch, 6)
		}
		if !bytes.Equal(snap.fAvatar, e.Avatar) {
			ch = append(ch, 7)
		}
		if !snap.fCreatedAt.Equal(e.CreatedAt) {
			ch = append(ch, 8)
		}
		if !sorm.TimePtrEq(snap.fDeletedAt, e.DeletedAt) {
			ch = append(ch, 9)
		}
		return ch
	},
	SetPK:         func(e *models.User, id int64) { e.ID = id },
	PKValue:       func(e *models.User) any { return e.ID },
	SoftDeleteCol: "deleted_at",
	SetDeleted:    func(e *models.User, t time.Time) { e.DeletedAt = &t },
	GetVersion:    func(e *models.User) int64 { return e.Version },
	SetVersion:    func(e *models.User, v int64) { e.Version = v },
}
