package sorm

import (
	"context"
	"fmt"
)

// inChunkSize — the key limit per WHERE ... IN (...) during eager loading:
// tens of thousands of parents won't hit DB placeholder limits.
const inChunkSize = 1000

func chunked(keys []any) [][]any {
	if len(keys) <= inChunkSize {
		return [][]any{keys}
	}
	var out [][]any
	for start := 0; start < len(keys); start += inChunkSize {
		end := min(start+inChunkSize, len(keys))
		out = append(out, keys[start:end])
	}
	return out
}

// HasMany — one-to-many relation descriptor. It knows both types, so every
// "two-type" operation (Include, Any) is a method on it: builder methods
// cannot introduce new type parameters.
//
// Accessor functions are generated by `sorm gen` — the runtime uses no reflection.
type HasMany[E, C any] struct {
	fkCol       string
	parentKey   func(*E) any
	childKey    func(*C) any
	initSlice   func(*E)      // marks the navigation as "loaded but empty"
	appendChild func(*E, *C)
}

func NewHasMany[E, C any](
	fkCol string,
	parentKey func(*E) any,
	childKey func(*C) any,
	initSlice func(*E),
	appendChild func(*E, *C),
) HasMany[E, C] {
	return HasMany[E, C]{fkCol, parentKey, childKey, initSlice, appendChild}
}

// Any filters the PARENT by its children: EXISTS (SELECT 1 FROM children WHERE fk = parent.pk AND preds).
// Returns a Pred[E]; feed it into a regular Where.
func (r HasMany[E, C]) Any(preds ...Pred[C]) Pred[E] {
	return r.exists(preds, false)
}

// None — NOT EXISTS: parents that have no matching children.
func (r HasMany[E, C]) None(preds ...Pred[C]) Pred[E] {
	return r.exists(preds, true)
}

func (r HasMany[E, C]) exists(preds []Pred[C], not bool) Pred[E] {
	pm, cm := metaFor[E](), metaFor[C]()
	return pred[E](existsNode{
		childTable:  cm.Table,
		fkCol:       r.fkCol,
		parentTable: pm.Table,
		parentPK:    pm.PK,
		deletedCol:  cm.SoftDeleteCol,
		preds:       nodesOf(preds),
		not:         not,
	})
}

// ChildOpt — an Include option: a child predicate (Pred[C]), child ordering
// (Order[C]), or a nested spec (IncludeSpec[C] — analogous to ThenInclude):
//
//	q.With(u.Posts.Include(
//	    p.Title.HasPrefix("Go"),      // child filter
//	    p.CreatedAt.Desc(),           // child order
//	    p.Comments.Include(),         // nested loading
//	))
type ChildOpt[C any] interface {
	applyChild(cfg *childCfg[C])
}

type childCfg[C any] struct {
	preds  []Pred[C]
	orders []Order[C]
	specs  []IncludeSpec[C]
}

func (p Pred[C]) applyChild(cfg *childCfg[C])        { cfg.preds = append(cfg.preds, p) }
func (o Order[C]) applyChild(cfg *childCfg[C])       { cfg.orders = append(cfg.orders, o) }
func (s IncludeSpec[C]) applyChild(cfg *childCfg[C]) { cfg.specs = append(cfg.specs, s) }

func childConfig[C any](opts []ChildOpt[C]) childCfg[C] {
	var cfg childCfg[C]
	for _, o := range opts {
		o.applyChild(&cfg)
	}
	return cfg
}

// Include — eager loading of children (split strategy: a separate query
// WHERE fk IN (pks) and in-memory distribution to parents).
// Options: Pred[C] (child filter), Order[C] (their order), IncludeSpec[C]
// (nested loading — analogous to ThenInclude).
func (r HasMany[E, C]) Include(opts ...ChildOpt[C]) IncludeSpec[E] {
	cfg := childConfig(opts)
	return IncludeSpec[E]{load: func(ctx context.Context, db DB, sess *Session, parents []*E) error {
		if len(parents) == 0 {
			return nil
		}
		keys := make([]any, 0, len(parents))
		byKey := make(map[any][]*E, len(parents))
		for _, p := range parents {
			k := r.parentKey(p)
			if _, seen := byKey[k]; !seen {
				keys = append(keys, k)
			}
			byKey[k] = append(byKey[k], p)
			r.initSlice(p) // a loaded empty relation = empty slice, not nil
		}

		var all []*C
		for _, chunk := range chunked(keys) {
			cq := Query[C](db).
				Where(pred[C](inNode{colRef{name: r.fkCol}, chunk, false})).
				Where(cfg.preds...).
				OrderBy(cfg.orders...)
			cq.sess = sess // Track tracks children too
			children, err := cq.All(ctx)
			if err != nil {
				return fmt.Errorf("include: %w", err)
			}
			for _, c := range children {
				for _, p := range byKey[r.childKey(c)] {
					r.appendChild(p, c)
				}
			}
			all = append(all, children...)
		}
		return runChildSpecs(ctx, db, sess, cfg.specs, all)
	}}
}

// IncludeSpec — an eager loading specification closed over the parent
// entity; created by relation descriptor methods, executed by the builder.
type IncludeSpec[E any] struct {
	load func(ctx context.Context, db DB, sess *Session, parents []*E) error
}

// runChildSpecs executes nested Includes over the loaded children.
func runChildSpecs[C any](ctx context.Context, db DB, sess *Session, specs []IncludeSpec[C], children []*C) error {
	for _, sp := range specs {
		if err := sp.load(ctx, db, sess, children); err != nil {
			return err
		}
	}
	return nil
}

// BelongsTo — many-to-one relation descriptor (child → parent).
// Accessor functions are generated by `sorm gen`.
type BelongsTo[C, P any] struct {
	fkCol     string
	childFK   func(*C) any
	setParent func(*C, *P)
}

func NewBelongsTo[C, P any](
	fkCol string,
	childFK func(*C) any,
	setParent func(*C, *P),
) BelongsTo[C, P] {
	return BelongsTo[C, P]{fkCol, childFK, setParent}
}

// Is filters the CHILD by parent attributes:
// EXISTS (SELECT 1 FROM parents WHERE parents.pk = children.fk AND preds).
func (r BelongsTo[C, P]) Is(preds ...Pred[P]) Pred[C] {
	cm, pm := metaFor[C](), metaFor[P]()
	return pred[C](existsNode{
		childTable:  pm.Table,
		fkCol:       pm.PK,
		parentTable: cm.Table,
		parentPK:    r.fkCol,
		deletedCol:  pm.SoftDeleteCol,
		preds:       nodesOf(preds),
	})
}

// Include — eager loading of the parent: one query WHERE pk IN (children's fks)
// and distribution to children. Pred[P] options filter the parents; a child
// whose parent is filtered out keeps a nil navigation. IncludeSpec[P] options —
// nested loading of the parent's relations.
func (r BelongsTo[C, P]) Include(opts ...ChildOpt[P]) IncludeSpec[C] {
	cfg := childConfig(opts)
	return IncludeSpec[C]{load: func(ctx context.Context, db DB, sess *Session, children []*C) error {
		if len(children) == 0 {
			return nil
		}
		pm := metaFor[P]()

		keys := make([]any, 0, len(children))
		seen := map[any]bool{}
		for _, c := range children {
			k := r.childFK(c)
			if isZero(k) || seen[k] {
				continue
			}
			seen[k] = true
			keys = append(keys, k)
		}
		if len(keys) == 0 {
			return nil
		}

		byPK := map[any]*P{}
		var all []*P
		for _, chunk := range chunked(keys) {
			pq := Query[P](db).
				Where(pred[P](inNode{colRef{name: pm.PK}, chunk, false})).
				Where(cfg.preds...)
			pq.sess = sess // Track tracks parents too
			parents, err := pq.All(ctx)
			if err != nil {
				return fmt.Errorf("include: %w", err)
			}
			for _, p := range parents {
				byPK[pm.PKValue(p)] = p
			}
			all = append(all, parents...)
		}
		for _, c := range children {
			if p, ok := byPK[r.childFK(c)]; ok {
				r.setParent(c, p)
			}
		}
		return runChildSpecs(ctx, db, sess, cfg.specs, all)
	}}
}

// HasOne — one-to-one relation (FK on the child side C, *C navigation on E).
// A missing child after Include is indistinguishable from "not loaded" (the
// pointer stays nil) — unlike hasMany, where an empty slice ≠ nil.
type HasOne[E, C any] struct {
	fkCol     string
	parentKey func(*E) any
	childKey  func(*C) any
	setChild  func(*E, *C)
}

func NewHasOne[E, C any](
	fkCol string,
	parentKey func(*E) any,
	childKey func(*C) any,
	setChild func(*E, *C),
) HasOne[E, C] {
	return HasOne[E, C]{fkCol, parentKey, childKey, setChild}
}

// Any filters the parent by the child (EXISTS); None — absence of a child.
func (r HasOne[E, C]) Any(preds ...Pred[C]) Pred[E]  { return r.exists(preds, false) }
func (r HasOne[E, C]) None(preds ...Pred[C]) Pred[E] { return r.exists(preds, true) }

func (r HasOne[E, C]) exists(preds []Pred[C], not bool) Pred[E] {
	pm, cm := metaFor[E](), metaFor[C]()
	return pred[E](existsNode{
		childTable:  cm.Table,
		fkCol:       r.fkCol,
		parentTable: pm.Table,
		parentPK:    pm.PK,
		deletedCol:  cm.SoftDeleteCol,
		preds:       nodesOf(preds),
		not:         not,
	})
}

// Include — eager loading of the single child (WHERE fk IN (pks)).
func (r HasOne[E, C]) Include(opts ...ChildOpt[C]) IncludeSpec[E] {
	cfg := childConfig(opts)
	return IncludeSpec[E]{load: func(ctx context.Context, db DB, sess *Session, parents []*E) error {
		if len(parents) == 0 {
			return nil
		}
		keys := make([]any, 0, len(parents))
		byKey := make(map[any][]*E, len(parents))
		for _, p := range parents {
			k := r.parentKey(p)
			if _, seen := byKey[k]; !seen {
				keys = append(keys, k)
			}
			byKey[k] = append(byKey[k], p)
		}

		var all []*C
		for _, chunk := range chunked(keys) {
			cq := Query[C](db).
				Where(pred[C](inNode{colRef{name: r.fkCol}, chunk, false})).
				Where(cfg.preds...)
			cq.sess = sess
			children, err := cq.All(ctx)
			if err != nil {
				return fmt.Errorf("include: %w", err)
			}
			for _, c := range children {
				for _, p := range byKey[r.childKey(c)] {
					r.setChild(p, c)
				}
			}
			all = append(all, children...)
		}
		return runChildSpecs(ctx, db, sess, cfg.specs, all)
	}}
}
