// Package codegen генерирует пакет sormgen из разобранной схемы:
// типизированные дескрипторы колонок, мету с пополевыми Scan/Snapshot/Diff
// (ноль рефлексии в рантайме) — компактно и diff-friendly.
package codegen

import (
	"fmt"
	"go/format"
	"strings"

	"sorm"
	"sorm/internal/ddl"
	"sorm/internal/parse"
)

// Generate возвращает файлы сгенерированного пакета: имя файла → содержимое.
func Generate(s *parse.Schema) (map[string][]byte, error) {
	out := map[string][]byte{}
	for _, e := range s.Entities {
		src, err := genEntity(s, e)
		if err != nil {
			return nil, fmt.Errorf("%s: %w", e.Name, err)
		}
		formatted, err := format.Source(src)
		if err != nil {
			// Ошибка форматирования = баг генератора; показываем сырой код для отладки.
			return nil, fmt.Errorf("%s: generated code does not parse: %w\n%s", e.Name, err, src)
		}
		out[strings.ToLower(e.Name)+".go"] = formatted
	}

	// join-таблицы many2many: регистрация TableDef для миграций
	joins, err := ddl.JoinTableDefs(s)
	if err != nil {
		return nil, err
	}
	if len(joins) > 0 {
		src, err := genJoinTables(joins)
		if err != nil {
			return nil, err
		}
		out["jointables.go"] = src
	}
	return out, nil
}

func genJoinTables(joins []sorm.TableDef) ([]byte, error) {
	g := &gen{}
	g.pf("// Code generated by sorm gen. DO NOT EDIT.\n\npackage sormgen\n\nimport \"sorm\"\n\n")
	g.pf("func init() {\n")
	for _, def := range joins {
		g.pf("\tsorm.RegisterTable(sorm.TableDef{\n\t\tName: %q,\n\t\tColumns: []sorm.ColumnDef{\n", def.Name)
		for _, c := range def.Columns {
			g.pf("\t\t\t{Name: %q, GoKind: %q, PK: true", c.Name, c.GoKind)
			if c.SQLType != "" {
				g.pf(", SQLType: %q", c.SQLType)
			}
			g.pf(", RefTable: %q, RefCol: %q},\n", c.RefTable, c.RefCol)
		}
		g.pf("\t\t},\n\t})\n")
	}
	g.pf("}\n")
	formatted, err := format.Source([]byte(g.String()))
	if err != nil {
		return nil, fmt.Errorf("jointables: generated code does not parse: %w\n%s", err, g.String())
	}
	return formatted, nil
}

type gen struct{ strings.Builder }

func (g *gen) pf(format string, args ...any) { fmt.Fprintf(g, format, args...) }

func genEntity(s *parse.Schema, e parse.Entity) ([]byte, error) {
	g := &gen{}
	lname := lowerFirst(e.Name)

	needsTime, needsBytes, needsSlices := false, false, false
	for _, f := range e.Fields {
		if f.IsTime {
			needsTime = true
		}
		if f.IsBytes {
			needsBytes, needsSlices = true, true
		}
	}

	g.pf("// Code generated by sorm gen. DO NOT EDIT.\n\npackage sormgen\n\nimport (\n")
	if needsBytes {
		g.pf("\t\"bytes\"\n")
	}
	if needsSlices {
		g.pf("\t\"slices\"\n")
	}
	if needsTime {
		g.pf("\t\"time\"\n")
	}
	g.pf("\n\t\"sorm\"\n\n\tmodels %q\n)\n\n", s.PkgPath)

	entT := "models." + e.Name

	// --- дескрипторы колонок и связей ---
	g.pf("// %s — типизированные дескрипторы колонок %s.\nvar %s = struct {\n", e.Name, entT, e.Name)
	for _, f := range e.Fields {
		g.pf("\t%s %s\n", f.GoName, descType(entT, f))
	}
	hasManys := relationsOf(e, "hasMany")
	for _, r := range hasManys {
		g.pf("\t%s sorm.HasMany[%s, models.%s]\n", r.GoName, entT, r.Target)
	}
	belongTos := relationsOf(e, "belongsTo")
	for _, r := range belongTos {
		g.pf("\t%s sorm.BelongsTo[%s, models.%s]\n", r.GoName, entT, r.Target)
	}
	m2ms := relationsOf(e, "many2many")
	for _, r := range m2ms {
		g.pf("\t%s sorm.ManyToMany[%s, models.%s]\n", r.GoName, entT, r.Target)
	}
	hasOnes := relationsOf(e, "hasOne")
	for _, r := range hasOnes {
		g.pf("\t%s sorm.HasOne[%s, models.%s]\n", r.GoName, entT, r.Target)
	}
	g.pf("}{\n")
	for _, f := range e.Fields {
		g.pf("\t%s: %s(%q, %q),\n", f.GoName, descCtor(entT, f), e.Table, f.Col)
	}
	for _, r := range hasManys {
		fkCol, err := fkColOf(s, r)
		if err != nil {
			return nil, err
		}
		childT := "models." + r.Target
		g.pf("\t%s: sorm.NewHasMany[%s, %s](\n", r.GoName, entT, childT)
		g.pf("\t\t%q,\n", fkCol)
		g.pf("\t\tfunc(e *%s) any { return e.%s },\n", entT, e.PK().GoName)
		g.pf("\t\tfunc(c *%s) any { return c.%s },\n", childT, r.FKField)
		g.pf("\t\tfunc(e *%s) { e.%s = []*%s{} },\n", entT, r.GoName, childT)
		g.pf("\t\tfunc(e *%s, c *%s) { e.%s = append(e.%s, c) },\n", entT, childT, r.GoName, r.GoName)
		g.pf("\t),\n")
	}
	for _, r := range belongTos {
		fk, ok := fieldByGoName(e, r.FKField)
		if !ok {
			return nil, fmt.Errorf("belongsTo %s: FK field %s not found", r.GoName, r.FKField)
		}
		parentT := "models." + r.Target
		g.pf("\t%s: sorm.NewBelongsTo[%s, %s](\n", r.GoName, entT, parentT)
		g.pf("\t\t%q,\n", fk.Col)
		g.pf("\t\tfunc(c *%s) any { return c.%s },\n", entT, fk.GoName)
		g.pf("\t\tfunc(c *%s, p *%s) { c.%s = p },\n", entT, parentT, r.GoName)
		g.pf("\t),\n")
	}
	for _, r := range m2ms {
		childT := "models." + r.Target
		g.pf("\t%s: sorm.NewManyToMany[%s, %s](\n", r.GoName, entT, childT)
		g.pf("\t\t%q, %q, %q,\n", r.JoinTable, parse.Snake(e.Name)+"_id", parse.Snake(r.Target)+"_id")
		g.pf("\t\tfunc(e *%s) { e.%s = []*%s{} },\n", entT, r.GoName, childT)
		g.pf("\t\tfunc(e *%s, c *%s) { e.%s = append(e.%s, c) },\n", entT, childT, r.GoName, r.GoName)
		g.pf("\t),\n")
	}
	for _, r := range hasOnes {
		fkCol, err := fkColOf(s, r)
		if err != nil {
			return nil, err
		}
		childT := "models." + r.Target
		g.pf("\t%s: sorm.NewHasOne[%s, %s](\n", r.GoName, entT, childT)
		g.pf("\t\t%q,\n", fkCol)
		g.pf("\t\tfunc(e *%s) any { return e.%s },\n", entT, e.PK().GoName)
		g.pf("\t\tfunc(c *%s) any { return c.%s },\n", childT, r.FKField)
		g.pf("\t\tfunc(e *%s, c *%s) { e.%s = c },\n", entT, childT, r.GoName)
		g.pf("\t),\n")
	}
	g.pf("}\n\n")

	// --- снапшот ---
	g.pf("type %sSnap struct {\n", lname)
	for i, f := range e.Fields {
		if i == e.PKIndex || i == e.VersionIndex {
			continue
		}
		g.pf("\t%s %s\n", snapField(f), snapType(f))
	}
	g.pf("}\n\n")

	// --- мета ---
	g.pf("func init() {\n\tsorm.Register(%sMeta)\n\tsorm.RegisterTable(%sTableDef)\n}\n\n", lname, lname)

	// --- описание таблицы для миграций (sorm/migrate, sorm schema) ---
	tdef, err := ddl.TableDefOf(s, e)
	if err != nil {
		return nil, err
	}
	g.pf("var %sTableDef = sorm.TableDef{\n\tName: %q,\n\tColumns: []sorm.ColumnDef{\n", lname, tdef.Name)
	for _, c := range tdef.Columns {
		g.pf("\t\t{Name: %q, GoKind: %q", c.Name, c.GoKind)
		if c.Nullable {
			g.pf(", Nullable: true")
		}
		if c.Unique {
			g.pf(", Unique: true")
		}
		if c.PK {
			g.pf(", PK: true")
		}
		if c.Auto {
			g.pf(", Auto: true")
		}
		if c.SQLType != "" {
			g.pf(", SQLType: %q", c.SQLType)
		}
		if c.RefTable != "" {
			g.pf(", RefTable: %q, RefCol: %q", c.RefTable, c.RefCol)
		}
		g.pf("},\n")
	}
	g.pf("\t},\n")
	if len(tdef.Indexes) > 0 || e.HasIndexesMethod {
		if e.HasIndexesMethod {
			// кастомные индексы модели (метод Indexes) объединяются с тегами
			g.pf("\tIndexes: append([]sorm.IndexDef{\n")
		} else {
			g.pf("\tIndexes: []sorm.IndexDef{\n")
		}
		for _, ix := range tdef.Indexes {
			g.pf("\t\t{Name: %q, Columns: []string{%s}, Unique: %v},\n",
				ix.Name, quotedList(ix.Columns), ix.Unique)
		}
		if e.HasIndexesMethod {
			g.pf("\t}, %s{}.Indexes()...),\n", entT)
		} else {
			g.pf("\t},\n")
		}
	}
	g.pf("}\n\n")
	g.pf("var %sMeta = sorm.Meta[%s]{\n", lname, entT)
	g.pf("\tTable: %q,\n\tPK:    %q,\n", e.Table, e.PK().Col)
	if e.PK().Auto {
		g.pf("\tAuto:  true,\n")
	}
	if e.VersionIndex >= 0 {
		g.pf("\tVersionCol: %q,\n", e.Fields[e.VersionIndex].Col)
	}

	g.pf("\tSelectCols: []string{%s},\n", colList(e.Fields, func(f parse.Field) bool { return true }))
	g.pf("\tInsertCols: []string{%s},\n", colList(e.Fields, func(f parse.Field) bool { return !(f.PK && f.Auto) }))

	g.pf("\tScan: func(e *%s) []any {\n\t\treturn []any{", entT)
	for i, f := range e.Fields {
		if i > 0 {
			g.pf(", ")
		}
		g.pf("&e.%s", f.GoName)
	}
	g.pf("}\n\t},\n")

	g.pf("\tInsertValues: func(e *%s) []any {\n\t\treturn []any{", entT)
	first := true
	for i, f := range e.Fields {
		if f.PK && f.Auto {
			continue
		}
		if !first {
			g.pf(", ")
		}
		first = false
		g.pf("e.%s", e.Fields[i].GoName)
	}
	g.pf("}\n\t},\n")

	g.pf("\tValuesFor: func(e *%s, cols []int) []any {\n", entT)
	g.pf("\t\tout := make([]any, len(cols))\n\t\tfor i, c := range cols {\n\t\t\tswitch c {\n")
	for i, f := range e.Fields {
		g.pf("\t\t\tcase %d:\n\t\t\t\tout[i] = e.%s\n", i, f.GoName)
	}
	g.pf("\t\t\t}\n\t\t}\n\t\treturn out\n\t},\n")

	g.pf("\tSnapshot: func(e *%s) any {\n\t\treturn %sSnap{\n", entT, lname)
	for i, f := range e.Fields {
		if i == e.PKIndex || i == e.VersionIndex {
			continue
		}
		g.pf("\t\t\t%s: %s,\n", snapField(f), snapExpr(f))
	}
	g.pf("\t\t}\n\t},\n")

	g.pf("\tDiff: func(s any, e *%s) []int {\n\t\tsnap := s.(%sSnap)\n\t\tvar ch []int\n", entT, lname)
	for i, f := range e.Fields {
		if i == e.PKIndex || i == e.VersionIndex {
			continue
		}
		g.pf("\t\tif %s {\n\t\t\tch = append(ch, %d)\n\t\t}\n", diffCond(f), i)
	}
	g.pf("\t\treturn ch\n\t},\n")

	if pk := e.PK(); pk.Auto {
		if pk.TypeExpr == "int64" {
			g.pf("\tSetPK: func(e *%s, id int64) { e.%s = id },\n", entT, pk.GoName)
		} else {
			g.pf("\tSetPK: func(e *%s, id int64) { e.%s = %s(id) },\n", entT, pk.GoName, pk.TypeExpr)
		}
	}
	g.pf("\tPKValue: func(e *%s) any { return e.%s },\n", entT, e.PK().GoName)
	if e.VersionIndex >= 0 {
		vf := e.Fields[e.VersionIndex].GoName
		g.pf("\tGetVersion: func(e *%s) int64 { return e.%s },\n", entT, vf)
		g.pf("\tSetVersion: func(e *%s, v int64) { e.%s = v },\n", entT, vf)
	}

	// Refs: belongsTo-навигации — рёбра топосорта по экземплярам и FK-fixup.
	belongs := relationsOf(e, "belongsTo")
	if len(belongs) > 0 {
		g.pf("\tRefs: []sorm.Ref[%s]{\n", entT)
		var refTables []string
		for _, r := range belongs {
			fk, ok := fieldByGoName(e, r.FKField)
			if !ok {
				return nil, fmt.Errorf("belongsTo %s: FK field %s not found", r.GoName, r.FKField)
			}
			target, ok := entityByName(s, r.Target)
			if !ok {
				return nil, fmt.Errorf("belongsTo %s: target %s not found", r.GoName, r.Target)
			}
			refTables = append(refTables, target.Table)
			g.pf("\t\t{\n\t\t\tFKCol:   %q,\n\t\t\tNotNull: %v,\n", fk.Col, !fk.Nullable)
			g.pf("\t\t\tNav: func(e *%s) any {\n\t\t\t\tif e.%s == nil {\n\t\t\t\t\treturn nil\n\t\t\t\t}\n\t\t\t\treturn e.%s\n\t\t\t},\n",
				entT, r.GoName, r.GoName)
			g.pf("\t\t\tNavPK: func(e *%s) any { return e.%s.%s },\n", entT, r.GoName, target.PK().GoName)
			g.pf("\t\t\tSetFK: func(e *%s, pk any) { e.%s = pk.(%s) },\n", entT, fk.GoName, fk.TypeExpr)
			g.pf("\t\t\tFKIsZero: func(e *%s) bool { return e.%s == %s },\n", entT, fk.GoName, zeroExpr(fk))
			g.pf("\t\t},\n")
		}
		g.pf("\t},\n")
		g.pf("\tRefTables: []string{%s},\n", quotedList(refTables))
	}
	g.pf("}\n")

	return []byte(g.String()), nil
}

func descType(entT string, f parse.Field) string {
	switch f.Kind {
	case parse.KindBytes:
		return fmt.Sprintf("sorm.BytesCol[%s]", entT)
	case parse.KindStr:
		return fmt.Sprintf("sorm.StrCol[%s]", entT)
	case parse.KindOrd:
		return fmt.Sprintf("sorm.OrdCol[%s, %s]", entT, f.TypeExpr)
	default:
		return fmt.Sprintf("sorm.Col[%s, %s]", entT, f.TypeExpr)
	}
}

func descCtor(entT string, f parse.Field) string {
	switch f.Kind {
	case parse.KindBytes:
		return fmt.Sprintf("sorm.NewBytesCol[%s]", entT)
	case parse.KindStr:
		return fmt.Sprintf("sorm.NewStrCol[%s]", entT)
	case parse.KindOrd:
		return fmt.Sprintf("sorm.NewOrdCol[%s, %s]", entT, f.TypeExpr)
	default:
		return fmt.Sprintf("sorm.NewCol[%s, %s]", entT, f.TypeExpr)
	}
}

func snapField(f parse.Field) string { return "f" + f.GoName }

func snapType(f parse.Field) string {
	t := f.TypeExpr
	if f.Nullable {
		t = "*" + t
	}
	return t
}

// snapExpr — выражение снапшота поля: клонирование указателей, отбрасывание
// monotonic у time.Time, копирование []byte.
func snapExpr(f parse.Field) string {
	src := "e." + f.GoName
	switch {
	case f.IsBytes:
		return "slices.Clone(" + src + ")"
	case f.IsTime && f.Nullable:
		return "sorm.CloneTimePtr(" + src + ")"
	case f.IsTime:
		return src + ".Round(0)"
	case f.Nullable:
		return "sorm.ClonePtr(" + src + ")"
	default:
		return src
	}
}

// diffCond — условие «поле изменилось»: bytes.Equal для []byte, .Equal для
// time.Time, помощники для указателей — наивный != тут даёт панику или фантомы.
func diffCond(f parse.Field) string {
	snap, cur := "snap."+snapField(f), "e."+f.GoName
	switch {
	case f.IsBytes:
		return fmt.Sprintf("!bytes.Equal(%s, %s)", snap, cur)
	case f.IsTime && f.Nullable:
		return fmt.Sprintf("!sorm.TimePtrEq(%s, %s)", snap, cur)
	case f.IsTime:
		return fmt.Sprintf("!%s.Equal(%s)", snap, cur)
	case f.Nullable:
		return fmt.Sprintf("!sorm.PtrEq(%s, %s)", snap, cur)
	default:
		return fmt.Sprintf("%s != %s", snap, cur)
	}
}

func colList(fields []parse.Field, include func(parse.Field) bool) string {
	var parts []string
	for _, f := range fields {
		if include(f) {
			parts = append(parts, fmt.Sprintf("%q", f.Col))
		}
	}
	return strings.Join(parts, ", ")
}

func lowerFirst(s string) string { return strings.ToLower(s[:1]) + s[1:] }

func relationsOf(e parse.Entity, kind string) []parse.Relation {
	var out []parse.Relation
	for _, r := range e.Relations {
		if r.Kind == kind {
			out = append(out, r)
		}
	}
	return out
}

func fieldByGoName(e parse.Entity, goName string) (parse.Field, bool) {
	for _, f := range e.Fields {
		if f.GoName == goName {
			return f, true
		}
	}
	return parse.Field{}, false
}

func entityByName(s *parse.Schema, name string) (parse.Entity, bool) {
	for _, e := range s.Entities {
		if e.Name == name {
			return e, true
		}
	}
	return parse.Entity{}, false
}

// zeroExpr — литерал нулевого значения FK-колонки для FKIsZero.
func zeroExpr(f parse.Field) string {
	if f.Nullable {
		return "nil"
	}
	switch {
	case f.TypeExpr == "string":
		return `""`
	default:
		return "0" // числовые FK; иные типы FK вне MVP
	}
}

func quotedList(items []string) string {
	var parts []string
	for _, s := range items {
		parts = append(parts, fmt.Sprintf("%q", s))
	}
	return strings.Join(parts, ", ")
}

// fkColOf — имя FK-колонки на целевой («многие») стороне hasMany.
func fkColOf(s *parse.Schema, r parse.Relation) (string, error) {
	for _, e := range s.Entities {
		if e.Name != r.Target {
			continue
		}
		for _, f := range e.Fields {
			if f.GoName == r.FKField {
				return f.Col, nil
			}
		}
	}
	return "", fmt.Errorf("relation %s: FK field %s not found on %s", r.GoName, r.FKField, r.Target)
}
