// Package codegen generates the sormgen package from the parsed schema:
// typed column descriptors and meta with per-field Scan/Snapshot/Diff
// (zero reflection at runtime) — compact and diff-friendly.
package codegen

import (
	"fmt"
	"go/format"
	"strings"

	"github.com/dvislobokov/sorm"
	"github.com/dvislobokov/sorm/internal/ddl"
	"github.com/dvislobokov/sorm/internal/parse"
)

// Generate returns the generated package files: file name → contents.
func Generate(s *parse.Schema) (map[string][]byte, error) {
	out := map[string][]byte{}
	for _, e := range s.Entities {
		src, err := genEntity(s, e)
		if err != nil {
			return nil, fmt.Errorf("%s: %w", e.Name, err)
		}
		formatted, err := format.Source(src)
		if err != nil {
			// A formatting error means a generator bug; show the raw code for debugging.
			return nil, fmt.Errorf("%s: generated code does not parse: %w\n%s", e.Name, err, src)
		}
		out[strings.ToLower(e.Name)+".go"] = formatted
	}

	// many2many join tables: register TableDefs for migrations
	joins, err := ddl.JoinTableDefs(s)
	if err != nil {
		return nil, err
	}
	if len(joins) > 0 {
		src, err := genJoinTables(joins)
		if err != nil {
			return nil, err
		}
		out["jointables.go"] = src
	}
	return out, nil
}

func genJoinTables(joins []sorm.TableDef) ([]byte, error) {
	g := &gen{}
	g.pf("// Code generated by sorm gen. DO NOT EDIT.\n\npackage sormgen\n\nimport \"github.com/dvislobokov/sorm\"\n\n")
	g.pf("func init() {\n")
	for _, def := range joins {
		g.pf("\tsorm.RegisterTable(sorm.TableDef{\n\t\tName: %q,\n\t\tColumns: []sorm.ColumnDef{\n", def.Name)
		for _, c := range def.Columns {
			g.pf("\t\t\t{Name: %q, GoKind: %q, PK: true", c.Name, c.GoKind)
			if c.SQLType != "" {
				g.pf(", SQLType: %q", c.SQLType)
			}
			g.pf(", RefTable: %q, RefCol: %q},\n", c.RefTable, c.RefCol)
		}
		g.pf("\t\t},\n\t})\n")
	}
	g.pf("}\n")
	formatted, err := format.Source([]byte(g.String()))
	if err != nil {
		return nil, fmt.Errorf("jointables: generated code does not parse: %w\n%s", err, g.String())
	}
	return formatted, nil
}

type gen struct{ strings.Builder }

func (g *gen) pf(format string, args ...any) { fmt.Fprintf(g, format, args...) }

func genEntity(s *parse.Schema, e parse.Entity) ([]byte, error) {
	g := &gen{}
	lname := lowerFirst(e.Name)

	needsTime, needsBytes, needsSlices, needsUUID := false, false, false, false
	for _, f := range e.Fields {
		if f.IsTime {
			needsTime = true
		}
		if f.IsBytes {
			needsBytes, needsSlices = true, true
		}
		if f.BasicKind == "uuid" {
			needsUUID = true
		}
		if f.Kind == parse.KindJSON {
			needsBytes = true // json snapshots diff with bytes.Equal
		}
	}

	g.pf("// Code generated by sorm gen. DO NOT EDIT.\n\npackage sormgen\n\nimport (\n")
	if needsBytes {
		g.pf("\t\"bytes\"\n")
	}
	if needsSlices {
		g.pf("\t\"slices\"\n")
	}
	if needsTime {
		g.pf("\t\"time\"\n")
	}
	g.pf("\n\t\"github.com/dvislobokov/sorm\"\n")
	if needsUUID {
		g.pf("\t\"github.com/google/uuid\"\n")
	}
	g.pf("\n\tmodels %q\n)\n\n", s.PkgPath)

	entT := "models." + e.Name

	// --- column and relation descriptors ---
	g.pf("// %s holds typed column descriptors for %s.\nvar %s = struct {\n", e.Name, entT, e.Name)
	for _, f := range e.Fields {
		g.pf("\t%s %s\n", f.GoName, descType(entT, f))
		if len(f.JSONDoc) > 0 {
			// typed accessors for the fields of a struct-shaped json column
			g.pf("\t%sDoc %s\n", f.GoName, jsonDocTypeDecl(entT, f.JSONDoc, "\t"))
		}
	}
	hasManys := relationsOf(e, "hasMany")
	for _, r := range hasManys {
		g.pf("\t%s sorm.HasMany[%s, models.%s]\n", r.GoName, entT, r.Target)
	}
	belongTos := relationsOf(e, "belongsTo")
	for _, r := range belongTos {
		g.pf("\t%s sorm.BelongsTo[%s, models.%s]\n", r.GoName, entT, r.Target)
	}
	m2ms := relationsOf(e, "many2many")
	for _, r := range m2ms {
		g.pf("\t%s sorm.ManyToMany[%s, models.%s]\n", r.GoName, entT, r.Target)
	}
	hasOnes := relationsOf(e, "hasOne")
	for _, r := range hasOnes {
		g.pf("\t%s sorm.HasOne[%s, models.%s]\n", r.GoName, entT, r.Target)
	}
	g.pf("}{\n")
	for _, f := range e.Fields {
		g.pf("\t%s: %s(%q, %q),\n", f.GoName, descCtor(entT, f), e.Table, f.Col)
		if len(f.JSONDoc) > 0 {
			g.pf("\t%sDoc: %s,\n", f.GoName,
				jsonDocValue(entT, e.Table, f.Col, f.JSONDoc, nil, "\t"))
		}
	}
	for _, r := range hasManys {
		fk, err := fkFieldOf(s, r)
		if err != nil {
			return nil, err
		}
		childT := "models." + r.Target
		g.pf("\t%s: sorm.NewHasMany[%s, %s](\n", r.GoName, entT, childT)
		g.pf("\t\t%q,\n", fk.Col)
		g.pf("\t\tfunc(e *%s) any { return e.%s },\n", entT, e.PK().GoName)
		g.pf("\t\t%s,\n", fkValueFn(childT, fk))
		g.pf("\t\tfunc(e *%s) { e.%s = []*%s{} },\n", entT, r.GoName, childT)
		g.pf("\t\tfunc(e *%s, c *%s) { e.%s = append(e.%s, c) },\n", entT, childT, r.GoName, r.GoName)
		g.pf("\t),\n")
	}
	for _, r := range belongTos {
		fk, ok := fieldByGoName(e, r.FKField)
		if !ok {
			return nil, fmt.Errorf("belongsTo %s: FK field %s not found", r.GoName, r.FKField)
		}
		parentT := "models." + r.Target
		g.pf("\t%s: sorm.NewBelongsTo[%s, %s](\n", r.GoName, entT, parentT)
		g.pf("\t\t%q,\n", fk.Col)
		g.pf("\t\t%s,\n", fkValueFn(entT, fk))
		g.pf("\t\tfunc(c *%s, p *%s) { c.%s = p },\n", entT, parentT, r.GoName)
		g.pf("\t),\n")
	}
	for _, r := range m2ms {
		childT := "models." + r.Target
		g.pf("\t%s: sorm.NewManyToMany[%s, %s](\n", r.GoName, entT, childT)
		g.pf("\t\t%q, %q, %q,\n", r.JoinTable, parse.Snake(e.Name)+"_id", parse.Snake(r.Target)+"_id")
		g.pf("\t\tfunc(e *%s) { e.%s = []*%s{} },\n", entT, r.GoName, childT)
		g.pf("\t\tfunc(e *%s, c *%s) { e.%s = append(e.%s, c) },\n", entT, childT, r.GoName, r.GoName)
		g.pf("\t),\n")
	}
	for _, r := range hasOnes {
		fk, err := fkFieldOf(s, r)
		if err != nil {
			return nil, err
		}
		childT := "models." + r.Target
		g.pf("\t%s: sorm.NewHasOne[%s, %s](\n", r.GoName, entT, childT)
		g.pf("\t\t%q,\n", fk.Col)
		g.pf("\t\tfunc(e *%s) any { return e.%s },\n", entT, e.PK().GoName)
		g.pf("\t\t%s,\n", fkValueFn(childT, fk))
		g.pf("\t\tfunc(e *%s, c *%s) { e.%s = c },\n", entT, childT, r.GoName)
		g.pf("\t),\n")
	}
	g.pf("}\n\n")

	// --- snapshot ---
	g.pf("type %sSnap struct {\n", lname)
	for i, f := range e.Fields {
		if i == e.PKIndex || i == e.VersionIndex {
			continue
		}
		g.pf("\t%s %s\n", snapField(f), snapType(f))
	}
	g.pf("}\n\n")

	// --- meta ---
	g.pf("func init() {\n\tsorm.Register(%sMeta)\n\tsorm.RegisterTable(%sTableDef)\n}\n\n", lname, lname)

	// --- table definition for migrations (sorm/migrate, sorm schema) ---
	tdef, err := ddl.TableDefOf(s, e)
	if err != nil {
		return nil, err
	}
	g.pf("var %sTableDef = sorm.TableDef{\n\tName: %q,\n\tColumns: []sorm.ColumnDef{\n", lname, tdef.Name)
	for _, c := range tdef.Columns {
		g.pf("\t\t{Name: %q, GoKind: %q", c.Name, c.GoKind)
		if c.Nullable {
			g.pf(", Nullable: true")
		}
		if c.Unique {
			g.pf(", Unique: true")
		}
		if c.PK {
			g.pf(", PK: true")
		}
		if c.Auto {
			g.pf(", Auto: true")
		}
		if c.SQLType != "" {
			g.pf(", SQLType: %q", c.SQLType)
		}
		if c.RefTable != "" {
			g.pf(", RefTable: %q, RefCol: %q", c.RefTable, c.RefCol)
		}
		g.pf("},\n")
	}
	g.pf("\t},\n")
	if len(tdef.Indexes) > 0 || e.HasIndexesMethod {
		if e.HasIndexesMethod {
			// the model's custom indexes (Indexes method) are merged with tag-defined ones
			g.pf("\tIndexes: append([]sorm.IndexDef{\n")
		} else {
			g.pf("\tIndexes: []sorm.IndexDef{\n")
		}
		for _, ix := range tdef.Indexes {
			g.pf("\t\t{Name: %q, Columns: []string{%s}, Unique: %v},\n",
				ix.Name, quotedList(ix.Columns), ix.Unique)
		}
		if e.HasIndexesMethod {
			g.pf("\t}, %s{}.Indexes()...),\n", entT)
		} else {
			g.pf("\t},\n")
		}
	}
	g.pf("}\n\n")
	g.pf("var %sMeta = sorm.Meta[%s]{\n", lname, entT)
	g.pf("\tTable: %q,\n\tPK:    %q,\n", e.Table, e.PK().Col)
	if e.PK().Auto {
		g.pf("\tAuto:  true,\n")
	}
	if e.VersionIndex >= 0 {
		g.pf("\tVersionCol: %q,\n", e.Fields[e.VersionIndex].Col)
	}

	g.pf("\tSelectCols: []string{%s},\n", colList(e.Fields, func(f parse.Field) bool { return true }))
	g.pf("\tInsertCols: []string{%s},\n", colList(e.Fields, func(f parse.Field) bool { return !(f.PK && f.Auto) }))

	g.pf("\tScan: func(e *%s) []any {\n\t\treturn []any{", entT)
	for i, f := range e.Fields {
		if i > 0 {
			g.pf(", ")
		}
		g.pf("%s", scanTarget(f))
	}
	g.pf("}\n\t},\n")

	g.pf("\tInsertValues: func(e *%s) []any {\n\t\treturn []any{", entT)
	first := true
	for _, f := range e.Fields {
		if f.PK && f.Auto {
			continue
		}
		if !first {
			g.pf(", ")
		}
		first = false
		g.pf("%s", valueExpr(f))
	}
	g.pf("}\n\t},\n")

	g.pf("\tValuesFor: func(e *%s, cols []int) []any {\n", entT)
	g.pf("\t\tout := make([]any, len(cols))\n\t\tfor i, c := range cols {\n\t\t\tswitch c {\n")
	for i, f := range e.Fields {
		g.pf("\t\t\tcase %d:\n\t\t\t\tout[i] = %s\n", i, valueExpr(f))
	}
	g.pf("\t\t\t}\n\t\t}\n\t\treturn out\n\t},\n")

	g.pf("\tSnapshot: func(e *%s) any {\n\t\treturn %sSnap{\n", entT, lname)
	for i, f := range e.Fields {
		if i == e.PKIndex || i == e.VersionIndex {
			continue
		}
		g.pf("\t\t\t%s: %s,\n", snapField(f), snapExpr(f))
	}
	g.pf("\t\t}\n\t},\n")

	g.pf("\tDiff: func(s any, e *%s) []int {\n\t\tsnap := s.(%sSnap)\n\t\tvar ch []int\n", entT, lname)
	for i, f := range e.Fields {
		if i == e.PKIndex || i == e.VersionIndex {
			continue
		}
		g.pf("\t\tif %s {\n\t\t\tch = append(ch, %d)\n\t\t}\n", diffCond(f), i)
	}
	g.pf("\t\treturn ch\n\t},\n")

	if pk := e.PK(); pk.Auto {
		if pk.TypeExpr == "int64" {
			g.pf("\tSetPK: func(e *%s, id int64) { e.%s = id },\n", entT, pk.GoName)
		} else {
			g.pf("\tSetPK: func(e *%s, id int64) { e.%s = %s(id) },\n", entT, pk.GoName, pk.TypeExpr)
		}
	}
	g.pf("\tPKValue: func(e *%s) any { return e.%s },\n", entT, e.PK().GoName)
	if e.VersionIndex >= 0 {
		vf := e.Fields[e.VersionIndex].GoName
		g.pf("\tGetVersion: func(e *%s) int64 { return e.%s },\n", entT, vf)
		g.pf("\tSetVersion: func(e *%s, v int64) { e.%s = v },\n", entT, vf)
	}

	// Refs: belongsTo navigations — instance topo-sort edges and FK fixup.
	belongs := relationsOf(e, "belongsTo")
	if len(belongs) > 0 {
		g.pf("\tRefs: []sorm.Ref[%s]{\n", entT)
		var refTables []string
		for _, r := range belongs {
			fk, ok := fieldByGoName(e, r.FKField)
			if !ok {
				return nil, fmt.Errorf("belongsTo %s: FK field %s not found", r.GoName, r.FKField)
			}
			target, ok := entityByName(s, r.Target)
			if !ok {
				return nil, fmt.Errorf("belongsTo %s: target %s not found", r.GoName, r.Target)
			}
			refTables = append(refTables, target.Table)
			g.pf("\t\t{\n\t\t\tFKCol:   %q,\n\t\t\tNotNull: %v,\n", fk.Col, !fk.Nullable)
			g.pf("\t\t\tNav: func(e *%s) any {\n\t\t\t\tif e.%s == nil {\n\t\t\t\t\treturn nil\n\t\t\t\t}\n\t\t\t\treturn e.%s\n\t\t\t},\n",
				entT, r.GoName, r.GoName)
			g.pf("\t\t\tNavPK: func(e *%s) any { return e.%s.%s },\n", entT, r.GoName, target.PK().GoName)
			if fk.Nullable {
				// pointer FK: store the address of a copy of the parent's PK
				g.pf("\t\t\tSetFK: func(e *%s, pk any) { v := pk.(%s); e.%s = &v },\n", entT, fk.TypeExpr, fk.GoName)
			} else {
				g.pf("\t\t\tSetFK: func(e *%s, pk any) { e.%s = pk.(%s) },\n", entT, fk.GoName, fk.TypeExpr)
			}
			g.pf("\t\t\tFKIsZero: func(e *%s) bool { return e.%s == %s },\n", entT, fk.GoName, zeroExpr(fk))
			g.pf("\t\t},\n")
		}
		g.pf("\t},\n")
		g.pf("\tRefTables: []string{%s},\n", quotedList(refTables))
	}
	g.pf("}\n")

	return []byte(g.String()), nil
}

// jsonAccessorType — the runtime descriptor type for a JSON leaf.
func jsonAccessorType(entT string, f parse.JSONField) string {
	switch f.Kind {
	case "string":
		return fmt.Sprintf("sorm.JSONStr[%s]", entT)
	case "int":
		return fmt.Sprintf("sorm.JSONNum[%s, int64]", entT)
	case "float":
		return fmt.Sprintf("sorm.JSONNum[%s, float64]", entT)
	case "bool":
		return fmt.Sprintf("sorm.JSONBool[%s]", entT)
	case "array":
		return fmt.Sprintf("sorm.JSONArr[%s]", entT)
	}
	return ""
}

// jsonDocTypeDecl renders the anonymous struct type of a <Field>Doc block.
func jsonDocTypeDecl(entT string, fields []parse.JSONField, indent string) string {
	var b strings.Builder
	b.WriteString("struct {\n")
	for _, f := range fields {
		if f.Kind == "object" {
			fmt.Fprintf(&b, "%s\t%s %s\n", indent, f.GoName,
				jsonDocTypeDecl(entT, f.Fields, indent+"\t"))
			continue
		}
		fmt.Fprintf(&b, "%s\t%s %s\n", indent, f.GoName, jsonAccessorType(entT, f))
	}
	b.WriteString(indent + "}")
	return b.String()
}

// jsonDocValue renders the composite literal of a <Field>Doc block.
func jsonDocValue(entT, table, col string, fields []parse.JSONField, path []string, indent string) string {
	var b strings.Builder
	b.WriteString(jsonDocTypeDecl(entT, fields, indent) + "{\n")
	for _, f := range fields {
		p := append(append([]string{}, path...), f.Key)
		if f.Kind == "object" {
			fmt.Fprintf(&b, "%s\t%s: %s,\n", indent, f.GoName,
				jsonDocValue(entT, table, col, f.Fields, p, indent+"\t"))
			continue
		}
		ctor := strings.Replace(jsonAccessorType(entT, f), "sorm.JSON", "sorm.NewJSON", 1)
		fmt.Fprintf(&b, "%s\t%s: %s(%q, %q, %q),\n", indent, f.GoName, ctor, table, col, strings.Join(p, "."))
	}
	b.WriteString(indent + "}")
	return b.String()
}

// scanTarget — the rows.Scan destination for a field.
func scanTarget(f parse.Field) string {
	if f.Kind == parse.KindJSON {
		return "sorm.JSONScan(&e." + f.GoName + ")"
	}
	return "&e." + f.GoName
}

// valueExpr — the write-side value of a field (INSERT/UPDATE args).
func valueExpr(f parse.Field) string {
	if f.Kind == parse.KindJSON {
		return "sorm.JSONValue(e." + f.GoName + ")"
	}
	return "e." + f.GoName
}

func descType(entT string, f parse.Field) string {
	switch f.Kind {
	case parse.KindJSON:
		return fmt.Sprintf("sorm.JSONCol[%s]", entT)
	case parse.KindBytes:
		return fmt.Sprintf("sorm.BytesCol[%s]", entT)
	case parse.KindStr:
		return fmt.Sprintf("sorm.StrCol[%s]", entT)
	case parse.KindOrd:
		return fmt.Sprintf("sorm.OrdCol[%s, %s]", entT, f.TypeExpr)
	default:
		return fmt.Sprintf("sorm.Col[%s, %s]", entT, f.TypeExpr)
	}
}

func descCtor(entT string, f parse.Field) string {
	switch f.Kind {
	case parse.KindJSON:
		return fmt.Sprintf("sorm.NewJSONCol[%s]", entT)
	case parse.KindBytes:
		return fmt.Sprintf("sorm.NewBytesCol[%s]", entT)
	case parse.KindStr:
		return fmt.Sprintf("sorm.NewStrCol[%s]", entT)
	case parse.KindOrd:
		return fmt.Sprintf("sorm.NewOrdCol[%s, %s]", entT, f.TypeExpr)
	default:
		return fmt.Sprintf("sorm.NewCol[%s, %s]", entT, f.TypeExpr)
	}
}

func snapField(f parse.Field) string { return "f" + f.GoName }

func snapType(f parse.Field) string {
	if f.Kind == parse.KindJSON {
		return "[]byte" // marshaled form; diffed with bytes.Equal
	}
	t := f.TypeExpr
	if f.Nullable {
		t = "*" + t
	}
	return t
}

// snapExpr — snapshot expression for a field: clone pointers, strip the
// monotonic clock from time.Time, copy []byte.
func snapExpr(f parse.Field) string {
	src := "e." + f.GoName
	switch {
	case f.Kind == parse.KindJSON:
		return "sorm.JSONSnapshot(" + src + ")"
	case f.IsBytes:
		return "slices.Clone(" + src + ")"
	case f.IsTime && f.Nullable:
		return "sorm.CloneTimePtr(" + src + ")"
	case f.IsTime:
		return src + ".Round(0)"
	case f.Nullable:
		return "sorm.ClonePtr(" + src + ")"
	default:
		return src
	}
}

// diffCond — "field changed" condition: bytes.Equal for []byte, .Equal for
// time.Time, helpers for pointers — a naive != here panics or yields phantom diffs.
func diffCond(f parse.Field) string {
	snap, cur := "snap."+snapField(f), "e."+f.GoName
	switch {
	case f.Kind == parse.KindJSON:
		return fmt.Sprintf("!bytes.Equal(%s, sorm.JSONSnapshot(%s))", snap, cur)
	case f.IsBytes:
		return fmt.Sprintf("!bytes.Equal(%s, %s)", snap, cur)
	case f.IsTime && f.Nullable:
		return fmt.Sprintf("!sorm.TimePtrEq(%s, %s)", snap, cur)
	case f.IsTime:
		return fmt.Sprintf("!%s.Equal(%s)", snap, cur)
	case f.Nullable:
		return fmt.Sprintf("!sorm.PtrEq(%s, %s)", snap, cur)
	default:
		return fmt.Sprintf("%s != %s", snap, cur)
	}
}

func colList(fields []parse.Field, include func(parse.Field) bool) string {
	var parts []string
	for _, f := range fields {
		if include(f) {
			parts = append(parts, fmt.Sprintf("%q", f.Col))
		}
	}
	return strings.Join(parts, ", ")
}

func lowerFirst(s string) string { return strings.ToLower(s[:1]) + s[1:] }

func relationsOf(e parse.Entity, kind string) []parse.Relation {
	var out []parse.Relation
	for _, r := range e.Relations {
		if r.Kind == kind {
			out = append(out, r)
		}
	}
	return out
}

func fieldByGoName(e parse.Entity, goName string) (parse.Field, bool) {
	for _, f := range e.Fields {
		if f.GoName == goName {
			return f, true
		}
	}
	return parse.Field{}, false
}

func entityByName(s *parse.Schema, name string) (parse.Entity, bool) {
	for _, e := range s.Entities {
		if e.Name == name {
			return e, true
		}
	}
	return parse.Entity{}, false
}

// zeroExpr — zero-value literal of the FK column for FKIsZero.
func zeroExpr(f parse.Field) string {
	if f.Nullable {
		return "nil"
	}
	switch {
	case f.TypeExpr == "string":
		return `""`
	case f.BasicKind == "uuid":
		return "(uuid.UUID{})"
	default:
		return "0" // numeric FKs; other FK types are out of MVP scope
	}
}

func quotedList(items []string) string {
	var parts []string
	for _, s := range items {
		parts = append(parts, fmt.Sprintf("%q", s))
	}
	return strings.Join(parts, ", ")
}

// fkColOf — FK column name on the target ("many") side of hasMany.
func fkColOf(s *parse.Schema, r parse.Relation) (string, error) {
	f, err := fkFieldOf(s, r)
	if err != nil {
		return "", err
	}
	return f.Col, nil
}

// fkFieldOf — the FK field on the target ("many") side of hasMany/hasOne.
func fkFieldOf(s *parse.Schema, r parse.Relation) (parse.Field, error) {
	for _, e := range s.Entities {
		if e.Name != r.Target {
			continue
		}
		for _, f := range e.Fields {
			if f.GoName == r.FKField {
				return f, nil
			}
		}
	}
	return parse.Field{}, fmt.Errorf("relation %s: FK field %s not found on %s", r.GoName, r.FKField, r.Target)
}

// fkValueFn renders a `func(x *T) any` accessor for an FK column.
// Nullable (pointer) FKs are dereferenced so relation maps key by value,
// not by pointer address; nil stays nil.
func fkValueFn(recvT string, fk parse.Field) string {
	if !fk.Nullable {
		return fmt.Sprintf("func(c *%s) any { return c.%s }", recvT, fk.GoName)
	}
	return fmt.Sprintf(
		"func(c *%s) any {\n\t\tif c.%s == nil {\n\t\t\treturn nil\n\t\t}\n\t\treturn *c.%s\n\t}",
		recvT, fk.GoName, fk.GoName)
}
