// Code generated by sorm gen. DO NOT EDIT.

package sormgen

import (
	"time"

	"github.com/dvislobokov/sorm"
	"github.com/google/uuid"

	models "github.com/dvislobokov/sorm/examples/chat/internal/models"
)

// ApiToken holds typed column descriptors for models.ApiToken.
var ApiToken = struct {
	ID        sorm.Col[models.ApiToken, uuid.UUID]
	UserID    sorm.OrdCol[models.ApiToken, int64]
	Label     sorm.StrCol[models.ApiToken]
	ExpiresAt sorm.OrdCol[models.ApiToken, time.Time]
	CreatedAt sorm.OrdCol[models.ApiToken, time.Time]
	User      sorm.BelongsTo[models.ApiToken, models.User]
}{
	ID:        sorm.NewCol[models.ApiToken, uuid.UUID]("api_tokens", "id"),
	UserID:    sorm.NewOrdCol[models.ApiToken, int64]("api_tokens", "user_id"),
	Label:     sorm.NewStrCol[models.ApiToken]("api_tokens", "label"),
	ExpiresAt: sorm.NewOrdCol[models.ApiToken, time.Time]("api_tokens", "expires_at"),
	CreatedAt: sorm.NewOrdCol[models.ApiToken, time.Time]("api_tokens", "created_at"),
	User: sorm.NewBelongsTo[models.ApiToken, models.User](
		"user_id",
		func(c *models.ApiToken) any { return c.UserID },
		func(c *models.ApiToken, p *models.User) { c.User = p },
	),
}

type apiTokenSnap struct {
	fUserID    int64
	fLabel     string
	fExpiresAt *time.Time
	fCreatedAt time.Time
}

func init() {
	sorm.Register(apiTokenMeta)
	sorm.RegisterTable(apiTokenTableDef)
}

var apiTokenTableDef = sorm.TableDef{
	Name: "api_tokens",
	Columns: []sorm.ColumnDef{
		{Name: "id", GoKind: "uuid", PK: true},
		{Name: "user_id", GoKind: "int64", RefTable: "users", RefCol: "id"},
		{Name: "label", GoKind: "string"},
		{Name: "expires_at", GoKind: "time", Nullable: true},
		{Name: "created_at", GoKind: "time"},
	},
}

var apiTokenMeta = sorm.Meta[models.ApiToken]{
	Table:      "api_tokens",
	PK:         "id",
	SelectCols: []string{"id", "user_id", "label", "expires_at", "created_at"},
	InsertCols: []string{"id", "user_id", "label", "expires_at", "created_at"},
	Scan: func(e *models.ApiToken) []any {
		return []any{&e.ID, &e.UserID, &e.Label, &e.ExpiresAt, &e.CreatedAt}
	},
	InsertValues: func(e *models.ApiToken) []any {
		return []any{e.ID, e.UserID, e.Label, e.ExpiresAt, e.CreatedAt}
	},
	ValuesFor: func(e *models.ApiToken, cols []int) []any {
		out := make([]any, len(cols))
		for i, c := range cols {
			switch c {
			case 0:
				out[i] = e.ID
			case 1:
				out[i] = e.UserID
			case 2:
				out[i] = e.Label
			case 3:
				out[i] = e.ExpiresAt
			case 4:
				out[i] = e.CreatedAt
			}
		}
		return out
	},
	Snapshot: func(e *models.ApiToken) any {
		return apiTokenSnap{
			fUserID:    e.UserID,
			fLabel:     e.Label,
			fExpiresAt: sorm.CloneTimePtr(e.ExpiresAt),
			fCreatedAt: e.CreatedAt.Round(0),
		}
	},
	Diff: func(s any, e *models.ApiToken) []int {
		snap := s.(apiTokenSnap)
		var ch []int
		if snap.fUserID != e.UserID {
			ch = append(ch, 1)
		}
		if snap.fLabel != e.Label {
			ch = append(ch, 2)
		}
		if !sorm.TimePtrEq(snap.fExpiresAt, e.ExpiresAt) {
			ch = append(ch, 3)
		}
		if !snap.fCreatedAt.Equal(e.CreatedAt) {
			ch = append(ch, 4)
		}
		return ch
	},
	PKValue: func(e *models.ApiToken) any { return e.ID },
	TouchCreate: func(e *models.ApiToken, t time.Time) {
		if e.CreatedAt.IsZero() {
			e.CreatedAt = t
		}
	},
	Refs: []sorm.Ref[models.ApiToken]{
		{
			FKCol:   "user_id",
			NotNull: true,
			Nav: func(e *models.ApiToken) any {
				if e.User == nil {
					return nil
				}
				return e.User
			},
			NavPK:    func(e *models.ApiToken) any { return e.User.ID },
			SetFK:    func(e *models.ApiToken, pk any) { e.UserID = pk.(int64) },
			FKIsZero: func(e *models.ApiToken) bool { return e.UserID == 0 },
		},
	},
	RefTables: []string{"users"},
}
