// Code generated by sorm gen. DO NOT EDIT.

package sormgen

import (
	"bytes"
	"time"

	"github.com/dvislobokov/sorm"

	models "github.com/dvislobokov/sorm/examples/chat/internal/models"
)

// AuditLog holds typed column descriptors for models.AuditLog.
var AuditLog = struct {
	ID       sorm.OrdCol[models.AuditLog, int64]
	ActorID  sorm.OrdCol[models.AuditLog, int64]
	Action   sorm.StrCol[models.AuditLog]
	Entity   sorm.StrCol[models.AuditLog]
	EntityID sorm.OrdCol[models.AuditLog, int64]
	Details  sorm.JSONCol[models.AuditLog]
	At       sorm.OrdCol[models.AuditLog, time.Time]
}{
	ID:       sorm.NewOrdCol[models.AuditLog, int64]("audit_logs", "id"),
	ActorID:  sorm.NewOrdCol[models.AuditLog, int64]("audit_logs", "actor_id"),
	Action:   sorm.NewStrCol[models.AuditLog]("audit_logs", "action"),
	Entity:   sorm.NewStrCol[models.AuditLog]("audit_logs", "entity"),
	EntityID: sorm.NewOrdCol[models.AuditLog, int64]("audit_logs", "entity_id"),
	Details:  sorm.NewJSONCol[models.AuditLog]("audit_logs", "details"),
	At:       sorm.NewOrdCol[models.AuditLog, time.Time]("audit_logs", "at"),
}

type auditLogSnap struct {
	fActorID  *int64
	fAction   string
	fEntity   string
	fEntityID int64
	fDetails  []byte
	fAt       time.Time
}

func init() {
	sorm.Register(auditLogMeta)
	sorm.RegisterTable(auditLogTableDef)
}

var auditLogTableDef = sorm.TableDef{
	Name: "audit_logs",
	Columns: []sorm.ColumnDef{
		{Name: "id", GoKind: "int64", PK: true, Auto: true},
		{Name: "actor_id", GoKind: "int64", Nullable: true, RefTable: "users", RefCol: "id"},
		{Name: "action", GoKind: "string"},
		{Name: "entity", GoKind: "string"},
		{Name: "entity_id", GoKind: "int64"},
		{Name: "details", GoKind: "json", Nullable: true},
		{Name: "at", GoKind: "time"},
	},
	Indexes: append([]sorm.IndexDef{
		{Name: "idx_audit_logs_action", Columns: []string{"action"}, Unique: false},
	}, models.AuditLog{}.Indexes()...),
}

var auditLogMeta = sorm.Meta[models.AuditLog]{
	Table:      "audit_logs",
	PK:         "id",
	Auto:       true,
	SelectCols: []string{"id", "actor_id", "action", "entity", "entity_id", "details", "at"},
	InsertCols: []string{"actor_id", "action", "entity", "entity_id", "details", "at"},
	Scan: func(e *models.AuditLog) []any {
		return []any{&e.ID, &e.ActorID, &e.Action, &e.Entity, &e.EntityID, sorm.JSONScan(&e.Details), &e.At}
	},
	InsertValues: func(e *models.AuditLog) []any {
		return []any{e.ActorID, e.Action, e.Entity, e.EntityID, sorm.JSONValue(e.Details), e.At}
	},
	ValuesFor: func(e *models.AuditLog, cols []int) []any {
		out := make([]any, len(cols))
		for i, c := range cols {
			switch c {
			case 0:
				out[i] = e.ID
			case 1:
				out[i] = e.ActorID
			case 2:
				out[i] = e.Action
			case 3:
				out[i] = e.Entity
			case 4:
				out[i] = e.EntityID
			case 5:
				out[i] = sorm.JSONValue(e.Details)
			case 6:
				out[i] = e.At
			}
		}
		return out
	},
	Snapshot: func(e *models.AuditLog) any {
		return auditLogSnap{
			fActorID:  sorm.ClonePtr(e.ActorID),
			fAction:   e.Action,
			fEntity:   e.Entity,
			fEntityID: e.EntityID,
			fDetails:  sorm.JSONSnapshot(e.Details),
			fAt:       e.At.Round(0),
		}
	},
	Diff: func(s any, e *models.AuditLog) []int {
		snap := s.(auditLogSnap)
		var ch []int
		if !sorm.PtrEq(snap.fActorID, e.ActorID) {
			ch = append(ch, 1)
		}
		if snap.fAction != e.Action {
			ch = append(ch, 2)
		}
		if snap.fEntity != e.Entity {
			ch = append(ch, 3)
		}
		if snap.fEntityID != e.EntityID {
			ch = append(ch, 4)
		}
		if !bytes.Equal(snap.fDetails, sorm.JSONSnapshot(e.Details)) {
			ch = append(ch, 5)
		}
		if !snap.fAt.Equal(e.At) {
			ch = append(ch, 6)
		}
		return ch
	},
	SetPK:   func(e *models.AuditLog, id int64) { e.ID = id },
	PKValue: func(e *models.AuditLog) any { return e.ID },
	TouchCreate: func(e *models.AuditLog, t time.Time) {
		if e.At.IsZero() {
			e.At = t
		}
	},
}
