// Code generated by sorm gen. DO NOT EDIT.

package sormgen

import "github.com/dvislobokov/sorm"

func init() {
	sorm.RegisterTable(sorm.TableDef{
		Name: "room_members",
		Columns: []sorm.ColumnDef{
			{Name: "room_id", GoKind: "int64", PK: true, RefTable: "rooms", RefCol: "id"},
			{Name: "user_id", GoKind: "int64", PK: true, RefTable: "users", RefCol: "id"},
		},
	})
}
