// Code generated by sorm gen. DO NOT EDIT.

package sormgen

import (
	"bytes"
	"time"

	"github.com/dvislobokov/sorm"

	models "github.com/dvislobokov/sorm/examples/chat/internal/models"
)

// Message holds typed column descriptors for models.Message.
var Message = struct {
	ID         sorm.OrdCol[models.Message, int64]
	RoomID     sorm.OrdCol[models.Message, int64]
	AuthorID   sorm.OrdCol[models.Message, int64]
	Text       sorm.StrCol[models.Message]
	Payload    sorm.JSONCol[models.Message]
	PayloadDoc struct {
		Kind        sorm.JSONStr[models.Message]
		Mentions    sorm.JSONArr[models.Message]
		Attachments sorm.JSONArr[models.Message]
	}
	ReplyToID sorm.OrdCol[models.Message, int64]
	Version   sorm.OrdCol[models.Message, int64]
	CreatedAt sorm.OrdCol[models.Message, time.Time]
	UpdatedAt sorm.OrdCol[models.Message, time.Time]
	DeletedAt sorm.OrdCol[models.Message, time.Time]
	Room      sorm.BelongsTo[models.Message, models.Room]
	Author    sorm.BelongsTo[models.Message, models.User]
	ReplyTo   sorm.BelongsTo[models.Message, models.Message]
}{
	ID:       sorm.NewOrdCol[models.Message, int64]("messages", "id"),
	RoomID:   sorm.NewOrdCol[models.Message, int64]("messages", "room_id"),
	AuthorID: sorm.NewOrdCol[models.Message, int64]("messages", "author_id"),
	Text:     sorm.NewStrCol[models.Message]("messages", "text"),
	Payload:  sorm.NewJSONCol[models.Message]("messages", "payload"),
	PayloadDoc: struct {
		Kind        sorm.JSONStr[models.Message]
		Mentions    sorm.JSONArr[models.Message]
		Attachments sorm.JSONArr[models.Message]
	}{
		Kind:        sorm.NewJSONStr[models.Message]("messages", "payload", "kind"),
		Mentions:    sorm.NewJSONArr[models.Message]("messages", "payload", "mentions"),
		Attachments: sorm.NewJSONArr[models.Message]("messages", "payload", "attachments"),
	},
	ReplyToID: sorm.NewOrdCol[models.Message, int64]("messages", "reply_to_id"),
	Version:   sorm.NewOrdCol[models.Message, int64]("messages", "version"),
	CreatedAt: sorm.NewOrdCol[models.Message, time.Time]("messages", "created_at"),
	UpdatedAt: sorm.NewOrdCol[models.Message, time.Time]("messages", "updated_at"),
	DeletedAt: sorm.NewOrdCol[models.Message, time.Time]("messages", "deleted_at"),
	Room: sorm.NewBelongsTo[models.Message, models.Room](
		"room_id",
		func(c *models.Message) any { return c.RoomID },
		func(c *models.Message, p *models.Room) { c.Room = p },
	),
	Author: sorm.NewBelongsTo[models.Message, models.User](
		"author_id",
		func(c *models.Message) any { return c.AuthorID },
		func(c *models.Message, p *models.User) { c.Author = p },
	),
	ReplyTo: sorm.NewBelongsTo[models.Message, models.Message](
		"reply_to_id",
		func(c *models.Message) any {
			if c.ReplyToID == nil {
				return nil
			}
			return *c.ReplyToID
		},
		func(c *models.Message, p *models.Message) { c.ReplyTo = p },
	),
}

type messageSnap struct {
	fRoomID    int64
	fAuthorID  int64
	fText      string
	fPayload   []byte
	fReplyToID *int64
	fCreatedAt time.Time
	fUpdatedAt time.Time
	fDeletedAt *time.Time
}

func init() {
	sorm.Register(messageMeta)
	sorm.RegisterTable(messageTableDef)
}

var messageTableDef = sorm.TableDef{
	Name: "messages",
	Columns: []sorm.ColumnDef{
		{Name: "id", GoKind: "int64", PK: true, Auto: true},
		{Name: "room_id", GoKind: "int64", RefTable: "rooms", RefCol: "id"},
		{Name: "author_id", GoKind: "int64", RefTable: "users", RefCol: "id"},
		{Name: "text", GoKind: "string"},
		{Name: "payload", GoKind: "json", Nullable: true},
		{Name: "reply_to_id", GoKind: "int64", Nullable: true, RefTable: "messages", RefCol: "id"},
		{Name: "version", GoKind: "int64"},
		{Name: "created_at", GoKind: "time"},
		{Name: "updated_at", GoKind: "time"},
		{Name: "deleted_at", GoKind: "time", Nullable: true},
	},
	Indexes: []sorm.IndexDef{
		{Name: "idx_messages_room_created", Columns: []string{"room_id", "created_at"}, Unique: false},
	},
}

var messageMeta = sorm.Meta[models.Message]{
	Table:      "messages",
	PK:         "id",
	Auto:       true,
	VersionCol: "version",
	SelectCols: []string{"id", "room_id", "author_id", "text", "payload", "reply_to_id", "version", "created_at", "updated_at", "deleted_at"},
	InsertCols: []string{"room_id", "author_id", "text", "payload", "reply_to_id", "version", "created_at", "updated_at", "deleted_at"},
	Scan: func(e *models.Message) []any {
		return []any{&e.ID, &e.RoomID, &e.AuthorID, &e.Text, sorm.JSONScan(&e.Payload), &e.ReplyToID, &e.Version, &e.CreatedAt, &e.UpdatedAt, &e.DeletedAt}
	},
	InsertValues: func(e *models.Message) []any {
		return []any{e.RoomID, e.AuthorID, e.Text, sorm.JSONValue(e.Payload), e.ReplyToID, e.Version, e.CreatedAt, e.UpdatedAt, e.DeletedAt}
	},
	ValuesFor: func(e *models.Message, cols []int) []any {
		out := make([]any, len(cols))
		for i, c := range cols {
			switch c {
			case 0:
				out[i] = e.ID
			case 1:
				out[i] = e.RoomID
			case 2:
				out[i] = e.AuthorID
			case 3:
				out[i] = e.Text
			case 4:
				out[i] = sorm.JSONValue(e.Payload)
			case 5:
				out[i] = e.ReplyToID
			case 6:
				out[i] = e.Version
			case 7:
				out[i] = e.CreatedAt
			case 8:
				out[i] = e.UpdatedAt
			case 9:
				out[i] = e.DeletedAt
			}
		}
		return out
	},
	Snapshot: func(e *models.Message) any {
		return messageSnap{
			fRoomID:    e.RoomID,
			fAuthorID:  e.AuthorID,
			fText:      e.Text,
			fPayload:   sorm.JSONSnapshot(e.Payload),
			fReplyToID: sorm.ClonePtr(e.ReplyToID),
			fCreatedAt: e.CreatedAt.Round(0),
			fUpdatedAt: e.UpdatedAt.Round(0),
			fDeletedAt: sorm.CloneTimePtr(e.DeletedAt),
		}
	},
	Diff: func(s any, e *models.Message) []int {
		snap := s.(messageSnap)
		var ch []int
		if snap.fRoomID != e.RoomID {
			ch = append(ch, 1)
		}
		if snap.fAuthorID != e.AuthorID {
			ch = append(ch, 2)
		}
		if snap.fText != e.Text {
			ch = append(ch, 3)
		}
		if !bytes.Equal(snap.fPayload, sorm.JSONSnapshot(e.Payload)) {
			ch = append(ch, 4)
		}
		if !sorm.PtrEq(snap.fReplyToID, e.ReplyToID) {
			ch = append(ch, 5)
		}
		if !snap.fCreatedAt.Equal(e.CreatedAt) {
			ch = append(ch, 7)
		}
		if !snap.fUpdatedAt.Equal(e.UpdatedAt) {
			ch = append(ch, 8)
		}
		if !sorm.TimePtrEq(snap.fDeletedAt, e.DeletedAt) {
			ch = append(ch, 9)
		}
		return ch
	},
	SetPK:   func(e *models.Message, id int64) { e.ID = id },
	PKValue: func(e *models.Message) any { return e.ID },
	TouchCreate: func(e *models.Message, t time.Time) {
		if e.CreatedAt.IsZero() {
			e.CreatedAt = t
		}
	},
	TouchUpdate: func(e *models.Message, t time.Time) {
		e.UpdatedAt = t
	},
	GetVersion: func(e *models.Message) int64 { return e.Version },
	SetVersion: func(e *models.Message, v int64) { e.Version = v },
	Refs: []sorm.Ref[models.Message]{
		{
			FKCol:   "room_id",
			NotNull: true,
			Nav: func(e *models.Message) any {
				if e.Room == nil {
					return nil
				}
				return e.Room
			},
			NavPK:    func(e *models.Message) any { return e.Room.ID },
			SetFK:    func(e *models.Message, pk any) { e.RoomID = pk.(int64) },
			FKIsZero: func(e *models.Message) bool { return e.RoomID == 0 },
		},
		{
			FKCol:   "author_id",
			NotNull: true,
			Nav: func(e *models.Message) any {
				if e.Author == nil {
					return nil
				}
				return e.Author
			},
			NavPK:    func(e *models.Message) any { return e.Author.ID },
			SetFK:    func(e *models.Message, pk any) { e.AuthorID = pk.(int64) },
			FKIsZero: func(e *models.Message) bool { return e.AuthorID == 0 },
		},
		{
			FKCol:   "reply_to_id",
			NotNull: false,
			Nav: func(e *models.Message) any {
				if e.ReplyTo == nil {
					return nil
				}
				return e.ReplyTo
			},
			NavPK:    func(e *models.Message) any { return e.ReplyTo.ID },
			SetFK:    func(e *models.Message, pk any) { v := pk.(int64); e.ReplyToID = &v },
			FKIsZero: func(e *models.Message) bool { return e.ReplyToID == nil },
		},
	},
	RefTables: []string{"rooms", "users", "messages"},
}
