// Code generated by sorm gen. DO NOT EDIT.

package sormgen

import (
	"time"

	"github.com/dvislobokov/sorm"

	models "github.com/dvislobokov/sorm/examples/chat/internal/models"
)

// Room holds typed column descriptors for models.Room.
var Room = struct {
	ID        sorm.OrdCol[models.Room, int64]
	Slug      sorm.StrCol[models.Room]
	Title     sorm.StrCol[models.Room]
	Topic     sorm.StrCol[models.Room]
	OwnerID   sorm.OrdCol[models.Room, int64]
	CreatedAt sorm.OrdCol[models.Room, time.Time]
	Messages  sorm.HasMany[models.Room, models.Message]
	Owner     sorm.BelongsTo[models.Room, models.User]
	Members   sorm.ManyToMany[models.Room, models.User]
}{
	ID:        sorm.NewOrdCol[models.Room, int64]("rooms", "id"),
	Slug:      sorm.NewStrCol[models.Room]("rooms", "slug"),
	Title:     sorm.NewStrCol[models.Room]("rooms", "title"),
	Topic:     sorm.NewStrCol[models.Room]("rooms", "topic"),
	OwnerID:   sorm.NewOrdCol[models.Room, int64]("rooms", "owner_id"),
	CreatedAt: sorm.NewOrdCol[models.Room, time.Time]("rooms", "created_at"),
	Messages: sorm.NewHasMany[models.Room, models.Message](
		"room_id",
		func(e *models.Room) any { return e.ID },
		func(c *models.Message) any { return c.RoomID },
		func(e *models.Room) { e.Messages = []*models.Message{} },
		func(e *models.Room, c *models.Message) { e.Messages = append(e.Messages, c) },
	),
	Owner: sorm.NewBelongsTo[models.Room, models.User](
		"owner_id",
		func(c *models.Room) any { return c.OwnerID },
		func(c *models.Room, p *models.User) { c.Owner = p },
	),
	Members: sorm.NewManyToMany[models.Room, models.User](
		"room_members", "room_id", "user_id",
		func(e *models.Room) { e.Members = []*models.User{} },
		func(e *models.Room, c *models.User) { e.Members = append(e.Members, c) },
	),
}

type roomSnap struct {
	fSlug      string
	fTitle     string
	fTopic     *string
	fOwnerID   int64
	fCreatedAt time.Time
}

func init() {
	sorm.Register(roomMeta)
	sorm.RegisterTable(roomTableDef)
}

var roomTableDef = sorm.TableDef{
	Name: "rooms",
	Columns: []sorm.ColumnDef{
		{Name: "id", GoKind: "int64", PK: true, Auto: true},
		{Name: "slug", GoKind: "string", Unique: true},
		{Name: "title", GoKind: "string"},
		{Name: "topic", GoKind: "string", Nullable: true},
		{Name: "owner_id", GoKind: "int64", RefTable: "users", RefCol: "id"},
		{Name: "created_at", GoKind: "time"},
	},
}

var roomMeta = sorm.Meta[models.Room]{
	Table:      "rooms",
	PK:         "id",
	Auto:       true,
	SelectCols: []string{"id", "slug", "title", "topic", "owner_id", "created_at"},
	InsertCols: []string{"slug", "title", "topic", "owner_id", "created_at"},
	Scan: func(e *models.Room) []any {
		return []any{&e.ID, &e.Slug, &e.Title, &e.Topic, &e.OwnerID, &e.CreatedAt}
	},
	InsertValues: func(e *models.Room) []any {
		return []any{e.Slug, e.Title, e.Topic, e.OwnerID, e.CreatedAt}
	},
	ValuesFor: func(e *models.Room, cols []int) []any {
		out := make([]any, len(cols))
		for i, c := range cols {
			switch c {
			case 0:
				out[i] = e.ID
			case 1:
				out[i] = e.Slug
			case 2:
				out[i] = e.Title
			case 3:
				out[i] = e.Topic
			case 4:
				out[i] = e.OwnerID
			case 5:
				out[i] = e.CreatedAt
			}
		}
		return out
	},
	Snapshot: func(e *models.Room) any {
		return roomSnap{
			fSlug:      e.Slug,
			fTitle:     e.Title,
			fTopic:     sorm.ClonePtr(e.Topic),
			fOwnerID:   e.OwnerID,
			fCreatedAt: e.CreatedAt.Round(0),
		}
	},
	Diff: func(s any, e *models.Room) []int {
		snap := s.(roomSnap)
		var ch []int
		if snap.fSlug != e.Slug {
			ch = append(ch, 1)
		}
		if snap.fTitle != e.Title {
			ch = append(ch, 2)
		}
		if !sorm.PtrEq(snap.fTopic, e.Topic) {
			ch = append(ch, 3)
		}
		if snap.fOwnerID != e.OwnerID {
			ch = append(ch, 4)
		}
		if !snap.fCreatedAt.Equal(e.CreatedAt) {
			ch = append(ch, 5)
		}
		return ch
	},
	SetPK:   func(e *models.Room, id int64) { e.ID = id },
	PKValue: func(e *models.Room) any { return e.ID },
	TouchCreate: func(e *models.Room, t time.Time) {
		if e.CreatedAt.IsZero() {
			e.CreatedAt = t
		}
	},
	Refs: []sorm.Ref[models.Room]{
		{
			FKCol:   "owner_id",
			NotNull: true,
			Nav: func(e *models.Room) any {
				if e.Owner == nil {
					return nil
				}
				return e.Owner
			},
			NavPK:    func(e *models.Room) any { return e.Owner.ID },
			SetFK:    func(e *models.Room, pk any) { e.OwnerID = pk.(int64) },
			FKIsZero: func(e *models.Room) bool { return e.OwnerID == 0 },
		},
	},
	RefTables: []string{"users"},
}
