// Code generated by sorm gen. DO NOT EDIT.

package sormgen

import (
	"bytes"
	"slices"
	"time"

	"github.com/dvislobokov/sorm"

	models "github.com/dvislobokov/sorm/examples/chat/internal/models"
)

// User holds typed column descriptors for models.User.
var User = struct {
	ID       sorm.OrdCol[models.User, int64]
	Email    sorm.StrCol[models.User]
	Name     sorm.StrCol[models.User]
	Bio      sorm.StrCol[models.User]
	Status   sorm.OrdCol[models.User, models.UserStatus]
	Prefs    sorm.JSONCol[models.User]
	PrefsDoc struct {
		Theme  sorm.JSONStr[models.User]
		Lang   sorm.JSONStr[models.User]
		Notify struct {
			Email sorm.JSONBool[models.User]
			Push  sorm.JSONBool[models.User]
		}
	}
	Meta      sorm.JSONCol[models.User]
	Roles     sorm.ArrayCol[models.User, string]
	Balance   sorm.ScalarCol[models.User, models.Cents]
	Version   sorm.OrdCol[models.User, int64]
	CreatedAt sorm.OrdCol[models.User, time.Time]
	UpdatedAt sorm.OrdCol[models.User, time.Time]
	Tokens    sorm.HasMany[models.User, models.ApiToken]
	Rooms     sorm.ManyToMany[models.User, models.Room]
}{
	ID:     sorm.NewOrdCol[models.User, int64]("users", "id"),
	Email:  sorm.NewStrCol[models.User]("users", "email"),
	Name:   sorm.NewStrCol[models.User]("users", "name"),
	Bio:    sorm.NewStrCol[models.User]("users", "bio"),
	Status: sorm.NewOrdCol[models.User, models.UserStatus]("users", "status"),
	Prefs:  sorm.NewJSONCol[models.User]("users", "prefs"),
	PrefsDoc: struct {
		Theme  sorm.JSONStr[models.User]
		Lang   sorm.JSONStr[models.User]
		Notify struct {
			Email sorm.JSONBool[models.User]
			Push  sorm.JSONBool[models.User]
		}
	}{
		Theme: sorm.NewJSONStr[models.User]("users", "prefs", "theme"),
		Lang:  sorm.NewJSONStr[models.User]("users", "prefs", "lang"),
		Notify: struct {
			Email sorm.JSONBool[models.User]
			Push  sorm.JSONBool[models.User]
		}{
			Email: sorm.NewJSONBool[models.User]("users", "prefs", "notify.email"),
			Push:  sorm.NewJSONBool[models.User]("users", "prefs", "notify.push"),
		},
	},
	Meta:      sorm.NewJSONCol[models.User]("users", "meta"),
	Roles:     sorm.NewArrayCol[models.User, string]("users", "roles"),
	Balance:   sorm.NewScalarCol[models.User, models.Cents]("users", "balance"),
	Version:   sorm.NewOrdCol[models.User, int64]("users", "version"),
	CreatedAt: sorm.NewOrdCol[models.User, time.Time]("users", "created_at"),
	UpdatedAt: sorm.NewOrdCol[models.User, time.Time]("users", "updated_at"),
	Tokens: sorm.NewHasMany[models.User, models.ApiToken](
		"user_id",
		func(e *models.User) any { return e.ID },
		func(c *models.ApiToken) any { return c.UserID },
		func(e *models.User) { e.Tokens = []*models.ApiToken{} },
		func(e *models.User, c *models.ApiToken) { e.Tokens = append(e.Tokens, c) },
	),
	Rooms: sorm.NewManyToMany[models.User, models.Room](
		"room_members", "user_id", "room_id",
		func(e *models.User) { e.Rooms = []*models.Room{} },
		func(e *models.User, c *models.Room) { e.Rooms = append(e.Rooms, c) },
	),
}

type userSnap struct {
	fEmail     string
	fName      string
	fBio       *string
	fStatus    models.UserStatus
	fPrefs     []byte
	fMeta      []byte
	fRoles     []string
	fBalance   any
	fCreatedAt time.Time
	fUpdatedAt time.Time
}

func init() {
	sorm.Register(userMeta)
	sorm.RegisterTable(userTableDef)
}

var userTableDef = sorm.TableDef{
	Name: "users",
	Columns: []sorm.ColumnDef{
		{Name: "id", GoKind: "int64", PK: true, Auto: true},
		{Name: "email", GoKind: "string", Unique: true},
		{Name: "name", GoKind: "string"},
		{Name: "bio", GoKind: "string", Nullable: true},
		{Name: "status", GoKind: "string"},
		{Name: "prefs", GoKind: "json", Nullable: true},
		{Name: "meta", GoKind: "json", Nullable: true},
		{Name: "roles", GoKind: "array:string", Nullable: true},
		{Name: "balance", GoKind: "scalar", SQLType: "bigint"},
		{Name: "version", GoKind: "int64"},
		{Name: "created_at", GoKind: "time"},
		{Name: "updated_at", GoKind: "time"},
	},
}

var userMeta = sorm.Meta[models.User]{
	Table:      "users",
	PK:         "id",
	Auto:       true,
	VersionCol: "version",
	SelectCols: []string{"id", "email", "name", "bio", "status", "prefs", "meta", "roles", "balance", "version", "created_at", "updated_at"},
	InsertCols: []string{"email", "name", "bio", "status", "prefs", "meta", "roles", "balance", "version", "created_at", "updated_at"},
	Scan: func(e *models.User) []any {
		return []any{&e.ID, &e.Email, &e.Name, &e.Bio, &e.Status, sorm.JSONScan(&e.Prefs), sorm.JSONScan(&e.Meta), &e.Roles, &e.Balance, &e.Version, &e.CreatedAt, &e.UpdatedAt}
	},
	InsertValues: func(e *models.User) []any {
		return []any{e.Email, e.Name, e.Bio, e.Status, sorm.JSONValue(e.Prefs), sorm.JSONValue(e.Meta), e.Roles, e.Balance, e.Version, e.CreatedAt, e.UpdatedAt}
	},
	ValuesFor: func(e *models.User, cols []int) []any {
		out := make([]any, len(cols))
		for i, c := range cols {
			switch c {
			case 0:
				out[i] = e.ID
			case 1:
				out[i] = e.Email
			case 2:
				out[i] = e.Name
			case 3:
				out[i] = e.Bio
			case 4:
				out[i] = e.Status
			case 5:
				out[i] = sorm.JSONValue(e.Prefs)
			case 6:
				out[i] = sorm.JSONValue(e.Meta)
			case 7:
				out[i] = e.Roles
			case 8:
				out[i] = e.Balance
			case 9:
				out[i] = e.Version
			case 10:
				out[i] = e.CreatedAt
			case 11:
				out[i] = e.UpdatedAt
			}
		}
		return out
	},
	Snapshot: func(e *models.User) any {
		return userSnap{
			fEmail:     e.Email,
			fName:      e.Name,
			fBio:       sorm.ClonePtr(e.Bio),
			fStatus:    e.Status,
			fPrefs:     sorm.JSONSnapshot(e.Prefs),
			fMeta:      sorm.JSONSnapshot(e.Meta),
			fRoles:     slices.Clone(e.Roles),
			fBalance:   sorm.ScalarSnapshot(e.Balance),
			fCreatedAt: e.CreatedAt.Round(0),
			fUpdatedAt: e.UpdatedAt.Round(0),
		}
	},
	Diff: func(s any, e *models.User) []int {
		snap := s.(userSnap)
		var ch []int
		if snap.fEmail != e.Email {
			ch = append(ch, 1)
		}
		if snap.fName != e.Name {
			ch = append(ch, 2)
		}
		if !sorm.PtrEq(snap.fBio, e.Bio) {
			ch = append(ch, 3)
		}
		if snap.fStatus != e.Status {
			ch = append(ch, 4)
		}
		if !bytes.Equal(snap.fPrefs, sorm.JSONSnapshot(e.Prefs)) {
			ch = append(ch, 5)
		}
		if !bytes.Equal(snap.fMeta, sorm.JSONSnapshot(e.Meta)) {
			ch = append(ch, 6)
		}
		if !slices.Equal(snap.fRoles, e.Roles) {
			ch = append(ch, 7)
		}
		if snap.fBalance != sorm.ScalarSnapshot(e.Balance) {
			ch = append(ch, 8)
		}
		if !snap.fCreatedAt.Equal(e.CreatedAt) {
			ch = append(ch, 10)
		}
		if !snap.fUpdatedAt.Equal(e.UpdatedAt) {
			ch = append(ch, 11)
		}
		return ch
	},
	SetPK:   func(e *models.User, id int64) { e.ID = id },
	PKValue: func(e *models.User) any { return e.ID },
	TouchCreate: func(e *models.User, t time.Time) {
		if e.CreatedAt.IsZero() {
			e.CreatedAt = t
		}
	},
	TouchUpdate: func(e *models.User, t time.Time) {
		e.UpdatedAt = t
	},
	GetVersion: func(e *models.User) int64 { return e.Version },
	SetVersion: func(e *models.User, v int64) { e.Version = v },
}
