// Package ddl генерирует каноническую SQL-схему (CREATE TABLE) из
// разобранной схемы моделей — вход для Atlas-workflow через файл
// (`atlas migrate diff --to file://schema.sql`) и документация схемы.
// Программные миграции из кода — sorm/migrate (Atlas SDK).
package ddl

import (
	"fmt"
	"sort"
	"strings"

	"sorm"
	"sorm/internal/parse"
)

// ColumnDefOf — конвертация поля схемы в рантаймовое описание колонки
// (общий словарь ddl-генератора, кодогена и sorm/migrate).
func ColumnDefOf(s *parse.Schema, f parse.Field) (sorm.ColumnDef, error) {
	c := sorm.ColumnDef{
		Name:     f.Col,
		GoKind:   f.BasicKind,
		Nullable: f.Nullable || f.IsBytes,
		Unique:   f.Unique,
		PK:       f.PK,
		Auto:     f.Auto,
		SQLType:  f.SQLType,
	}
	if f.FK != "" {
		table, col, err := s.ResolveFK(f.FK)
		if err != nil {
			return sorm.ColumnDef{}, err
		}
		c.RefTable, c.RefCol = table, col
	}
	return c, nil
}

// TableDefOf — описание таблицы сущности.
func TableDefOf(s *parse.Schema, e parse.Entity) (sorm.TableDef, error) {
	def := sorm.TableDef{Name: e.Table}
	for _, f := range e.Fields {
		c, err := ColumnDefOf(s, f)
		if err != nil {
			return sorm.TableDef{}, fmt.Errorf("%s.%s: %w", e.Name, f.GoName, err)
		}
		def.Columns = append(def.Columns, c)
	}
	for _, ix := range e.Indexes {
		def.Indexes = append(def.Indexes, sorm.IndexDef{Name: ix.Name, Columns: ix.Cols, Unique: ix.Unique})
	}
	return def, nil
}

// Generate выдаёт DDL для диалекта: "postgres", "mysql", "sqlite".
// Таблицы упорядочены так, чтобы родители шли раньше детей (FK).
func Generate(s *parse.Schema, dialect string) (string, error) {
	q, err := quoter(dialect)
	if err != nil {
		return "", err
	}

	var b strings.Builder
	b.WriteString("-- Code generated by sorm schema. DO NOT EDIT.\n")
	fmt.Fprintf(&b, "-- dialect: %s\n\n", dialect)

	var defs []sorm.TableDef
	for _, e := range orderByFK(s.Entities) {
		def, err := TableDefOf(s, e)
		if err != nil {
			return "", err
		}
		defs = append(defs, def)
	}
	// join-таблицы many2many — после сущностей (их FK уже существуют)
	joins, err := JoinTableDefs(s)
	if err != nil {
		return "", err
	}
	defs = append(defs, joins...)

	for _, def := range defs {
		fmt.Fprintf(&b, "CREATE TABLE %s (\n", q(def.Name))
		var lines []string
		pkCols := compositePK(def)
		for _, c := range def.Columns {
			lines = append(lines, "  "+columnDDL(c, dialect, q, len(pkCols) > 1))
		}
		if len(pkCols) > 1 {
			quoted := make([]string, len(pkCols))
			for i, c := range pkCols {
				quoted[i] = q(c)
			}
			lines = append(lines, "  PRIMARY KEY ("+strings.Join(quoted, ", ")+")")
		}
		b.WriteString(strings.Join(lines, ",\n"))
		b.WriteString("\n);\n\n")

		for _, ix := range def.Indexes {
			stmt, err := indexDDL(def.Name, ix, dialect, q)
			if err != nil {
				return "", err
			}
			b.WriteString(stmt + "\n\n")
		}
	}
	return b.String(), nil
}

func compositePK(def sorm.TableDef) []string {
	var out []string
	for _, c := range def.Columns {
		if c.PK {
			out = append(out, c.Name)
		}
	}
	return out
}

// JoinTableDefs — описания join-таблиц many2many (дедуп по имени;
// колонки: snake(Entity)_id со ссылками на PK обеих сторон, композитный PK).
func JoinTableDefs(s *parse.Schema) ([]sorm.TableDef, error) {
	byName := map[string]parse.Entity{}
	for _, e := range s.Entities {
		byName[e.Name] = e
	}
	seen := map[string]bool{}
	var out []sorm.TableDef
	for _, e := range s.Entities {
		for _, r := range e.Relations {
			if r.Kind != "many2many" || seen[r.JoinTable] {
				continue
			}
			target, ok := byName[r.Target]
			if !ok {
				return nil, fmt.Errorf("many2many %s.%s: unknown target %s", e.Name, r.GoName, r.Target)
			}
			seen[r.JoinTable] = true
			out = append(out, sorm.TableDef{
				Name: r.JoinTable,
				Columns: []sorm.ColumnDef{
					joinCol(e), joinCol(target),
				},
			})
		}
	}
	return out, nil
}

func joinCol(e parse.Entity) sorm.ColumnDef {
	pk := e.PK()
	return sorm.ColumnDef{
		Name:     parse.Snake(e.Name) + "_id",
		GoKind:   pk.BasicKind,
		SQLType:  pk.SQLType,
		PK:       true,
		RefTable: e.Table,
		RefCol:   pk.Col,
	}
}

func columnDDL(c sorm.ColumnDef, dialect string, q func(string) string, compositePK bool) string {
	parts := []string{q(c.Name)}

	switch {
	case c.PK && compositePK:
		// PRIMARY KEY выносится в table-level constraint
		parts = append(parts, sorm.SQLTypeFor(dialect, c), "NOT NULL")
	case c.PK && c.Auto:
		switch dialect {
		case "mysql":
			parts = append(parts, sorm.SQLTypeFor(dialect, c), "AUTO_INCREMENT PRIMARY KEY")
		case "sqlite":
			// AUTOINCREMENT в SQLite работает только с INTEGER PRIMARY KEY.
			parts = append(parts, "INTEGER PRIMARY KEY AUTOINCREMENT")
		default:
			parts = append(parts, sorm.SQLTypeFor(dialect, c), "GENERATED ALWAYS AS IDENTITY PRIMARY KEY")
		}
	case c.PK:
		parts = append(parts, sorm.SQLTypeFor(dialect, c), "PRIMARY KEY")
	default:
		parts = append(parts, sorm.SQLTypeFor(dialect, c))
		if c.Nullable {
			parts = append(parts, "NULL")
		} else {
			parts = append(parts, "NOT NULL")
		}
		if c.Unique {
			parts = append(parts, "UNIQUE")
		}
	}

	if c.RefTable != "" {
		parts = append(parts, fmt.Sprintf("REFERENCES %s (%s)", q(c.RefTable), q(c.RefCol)))
	}
	return strings.Join(parts, " ")
}

// IndexDDL — CREATE INDEX для одного IndexDef (доступно rantime-миграциям
// и тестам).
func IndexDDL(table string, ix sorm.IndexDef, dialect string) (string, error) {
	q, err := quoter(dialect)
	if err != nil {
		return "", err
	}
	return indexDDL(table, ix, dialect, q)
}

// indexDDL — CREATE INDEX с поддержкой DESC, выражений, типа (USING gin /
// FULLTEXT) и частичных индексов (WHERE).
func indexDDL(table string, ix sorm.IndexDef, dialect string, q func(string) string) (string, error) {
	var parts []string
	for _, p := range ix.IndexParts() {
		expr := p.Expr
		if expr == "" {
			expr = q(p.Column)
		} else {
			expr = "(" + expr + ")"
		}
		if p.Desc {
			expr += " DESC"
		}
		parts = append(parts, expr)
	}

	kind := "INDEX"
	using := ""
	switch {
	case ix.Unique && ix.Type != "":
		return "", fmt.Errorf("index %s: unique несовместим с type", ix.Name)
	case ix.Unique:
		kind = "UNIQUE INDEX"
	case ix.Type != "":
		switch dialect {
		case "postgres":
			using = " USING " + strings.ToUpper(ix.Type)
		case "mysql":
			kind = strings.ToUpper(ix.Type) + " INDEX" // FULLTEXT INDEX / SPATIAL INDEX
		default:
			return "", fmt.Errorf("index %s: тип индекса не поддерживается на %s", ix.Name, dialect)
		}
	}

	stmt := fmt.Sprintf("CREATE %s %s ON %s%s (%s)",
		kind, q(ix.Name), q(table), using, strings.Join(parts, ", "))
	if ix.Where != "" {
		if dialect == "mysql" {
			return "", fmt.Errorf("index %s: частичные индексы не поддерживаются на mysql", ix.Name)
		}
		stmt += " WHERE " + ix.Where
	}
	return stmt + ";", nil
}

func quoter(dialect string) (func(string) string, error) {
	switch dialect {
	case "postgres", "sqlite":
		return func(s string) string { return `"` + s + `"` }, nil
	case "mysql":
		return func(s string) string { return "`" + s + "`" }, nil
	default:
		return nil, fmt.Errorf("unknown dialect %q (postgres|mysql|sqlite)", dialect)
	}
}

// orderByFK — родители раньше детей (FK-ссылки должны существовать).
func orderByFK(entities []parse.Entity) []parse.Entity {
	refs := map[string][]string{}
	for _, e := range entities {
		for _, f := range e.Fields {
			if f.FK != "" {
				target, _, _ := strings.Cut(f.FK, ".")
				if target != e.Name {
					refs[e.Name] = append(refs[e.Name], target)
				}
			}
		}
	}
	rank := map[string]int{}
	var depth func(name string, seen map[string]bool) int
	depth = func(name string, seen map[string]bool) int {
		if r, ok := rank[name]; ok {
			return r
		}
		if seen[name] {
			return 0
		}
		seen[name] = true
		max := 0
		for _, p := range refs[name] {
			if d := depth(p, seen) + 1; d > max {
				max = d
			}
		}
		rank[name] = max
		return max
	}
	out := append([]parse.Entity(nil), entities...)
	for _, e := range out {
		depth(e.Name, map[string]bool{})
	}
	sort.SliceStable(out, func(i, j int) bool { return rank[out[i].Name] < rank[out[j].Name] })
	return out
}
