// Package ddl генерирует каноническую SQL-схему (CREATE TABLE) из
// разобранной схемы моделей — вход для Atlas-workflow через файл
// (`atlas migrate diff --to file://schema.sql`) и документация схемы.
// Программные миграции из кода — sorm/migrate (Atlas SDK).
package ddl

import (
	"fmt"
	"sort"
	"strings"

	"sorm"
	"sorm/internal/parse"
)

// ColumnDefOf — конвертация поля схемы в рантаймовое описание колонки
// (общий словарь ddl-генератора, кодогена и sorm/migrate).
func ColumnDefOf(s *parse.Schema, f parse.Field) (sorm.ColumnDef, error) {
	c := sorm.ColumnDef{
		Name:     f.Col,
		GoKind:   f.BasicKind,
		Nullable: f.Nullable || f.IsBytes,
		Unique:   f.Unique,
		PK:       f.PK,
		Auto:     f.Auto,
		SQLType:  f.SQLType,
	}
	if f.FK != "" {
		table, col, err := s.ResolveFK(f.FK)
		if err != nil {
			return sorm.ColumnDef{}, err
		}
		c.RefTable, c.RefCol = table, col
	}
	return c, nil
}

// TableDefOf — описание таблицы сущности.
func TableDefOf(s *parse.Schema, e parse.Entity) (sorm.TableDef, error) {
	def := sorm.TableDef{Name: e.Table}
	for _, f := range e.Fields {
		c, err := ColumnDefOf(s, f)
		if err != nil {
			return sorm.TableDef{}, fmt.Errorf("%s.%s: %w", e.Name, f.GoName, err)
		}
		def.Columns = append(def.Columns, c)
	}
	return def, nil
}

// Generate выдаёт DDL для диалекта: "postgres", "mysql", "sqlite".
// Таблицы упорядочены так, чтобы родители шли раньше детей (FK).
func Generate(s *parse.Schema, dialect string) (string, error) {
	q, err := quoter(dialect)
	if err != nil {
		return "", err
	}

	var b strings.Builder
	b.WriteString("-- Code generated by sorm schema. DO NOT EDIT.\n")
	fmt.Fprintf(&b, "-- dialect: %s\n\n", dialect)

	for _, e := range orderByFK(s.Entities) {
		def, err := TableDefOf(s, e)
		if err != nil {
			return "", err
		}
		fmt.Fprintf(&b, "CREATE TABLE %s (\n", q(def.Name))
		var lines []string
		for _, c := range def.Columns {
			lines = append(lines, "  "+columnDDL(c, dialect, q))
		}
		b.WriteString(strings.Join(lines, ",\n"))
		b.WriteString("\n);\n\n")
	}
	return b.String(), nil
}

func columnDDL(c sorm.ColumnDef, dialect string, q func(string) string) string {
	parts := []string{q(c.Name)}

	switch {
	case c.PK && c.Auto:
		switch dialect {
		case "mysql":
			parts = append(parts, sorm.SQLTypeFor(dialect, c), "AUTO_INCREMENT PRIMARY KEY")
		case "sqlite":
			// AUTOINCREMENT в SQLite работает только с INTEGER PRIMARY KEY.
			parts = append(parts, "INTEGER PRIMARY KEY AUTOINCREMENT")
		default:
			parts = append(parts, sorm.SQLTypeFor(dialect, c), "GENERATED ALWAYS AS IDENTITY PRIMARY KEY")
		}
	case c.PK:
		parts = append(parts, sorm.SQLTypeFor(dialect, c), "PRIMARY KEY")
	default:
		parts = append(parts, sorm.SQLTypeFor(dialect, c))
		if c.Nullable {
			parts = append(parts, "NULL")
		} else {
			parts = append(parts, "NOT NULL")
		}
		if c.Unique {
			parts = append(parts, "UNIQUE")
		}
	}

	if c.RefTable != "" {
		parts = append(parts, fmt.Sprintf("REFERENCES %s (%s)", q(c.RefTable), q(c.RefCol)))
	}
	return strings.Join(parts, " ")
}

func quoter(dialect string) (func(string) string, error) {
	switch dialect {
	case "postgres", "sqlite":
		return func(s string) string { return `"` + s + `"` }, nil
	case "mysql":
		return func(s string) string { return "`" + s + "`" }, nil
	default:
		return nil, fmt.Errorf("unknown dialect %q (postgres|mysql|sqlite)", dialect)
	}
}

// orderByFK — родители раньше детей (FK-ссылки должны существовать).
func orderByFK(entities []parse.Entity) []parse.Entity {
	refs := map[string][]string{}
	for _, e := range entities {
		for _, f := range e.Fields {
			if f.FK != "" {
				target, _, _ := strings.Cut(f.FK, ".")
				if target != e.Name {
					refs[e.Name] = append(refs[e.Name], target)
				}
			}
		}
	}
	rank := map[string]int{}
	var depth func(name string, seen map[string]bool) int
	depth = func(name string, seen map[string]bool) int {
		if r, ok := rank[name]; ok {
			return r
		}
		if seen[name] {
			return 0
		}
		seen[name] = true
		max := 0
		for _, p := range refs[name] {
			if d := depth(p, seen) + 1; d > max {
				max = d
			}
		}
		rank[name] = max
		return max
	}
	out := append([]parse.Entity(nil), entities...)
	for _, e := range out {
		depth(e.Name, map[string]bool{})
	}
	sort.SliceStable(out, func(i, j int) bool { return rank[out[i].Name] < rank[out[j].Name] })
	return out
}
