// Code generated by sorm gen. DO NOT EDIT.

package sormgen

import (
	"slices"

	"github.com/dvislobokov/sorm"

	models "github.com/dvislobokov/sorm/internal/pgmodels"
)

// Article holds typed column descriptors for models.Article.
var Article = struct {
	ID    sorm.OrdCol[models.Article, int64]
	Title sorm.StrCol[models.Article]
	Tags  sorm.ArrayCol[models.Article, string]
	Nums  sorm.ArrayCol[models.Article, int64]
}{
	ID:    sorm.NewOrdCol[models.Article, int64]("articles", "id"),
	Title: sorm.NewStrCol[models.Article]("articles", "title"),
	Tags:  sorm.NewArrayCol[models.Article, string]("articles", "tags"),
	Nums:  sorm.NewArrayCol[models.Article, int64]("articles", "nums"),
}

type articleSnap struct {
	fTitle string
	fTags  []string
	fNums  []int64
}

func init() {
	sorm.Register(articleMeta)
	sorm.RegisterTable(articleTableDef)
}

var articleTableDef = sorm.TableDef{
	Name: "articles",
	Columns: []sorm.ColumnDef{
		{Name: "id", GoKind: "int64", PK: true, Auto: true},
		{Name: "title", GoKind: "string"},
		{Name: "tags", GoKind: "array:string", Nullable: true},
		{Name: "nums", GoKind: "array:int64", Nullable: true},
	},
}

var articleMeta = sorm.Meta[models.Article]{
	Table:      "articles",
	PK:         "id",
	Auto:       true,
	SelectCols: []string{"id", "title", "tags", "nums"},
	InsertCols: []string{"title", "tags", "nums"},
	Scan: func(e *models.Article) []any {
		return []any{&e.ID, &e.Title, &e.Tags, &e.Nums}
	},
	InsertValues: func(e *models.Article) []any {
		return []any{e.Title, e.Tags, e.Nums}
	},
	ValuesFor: func(e *models.Article, cols []int) []any {
		out := make([]any, len(cols))
		for i, c := range cols {
			switch c {
			case 0:
				out[i] = e.ID
			case 1:
				out[i] = e.Title
			case 2:
				out[i] = e.Tags
			case 3:
				out[i] = e.Nums
			}
		}
		return out
	},
	Snapshot: func(e *models.Article) any {
		return articleSnap{
			fTitle: e.Title,
			fTags:  slices.Clone(e.Tags),
			fNums:  slices.Clone(e.Nums),
		}
	},
	Diff: func(s any, e *models.Article) []int {
		snap := s.(articleSnap)
		var ch []int
		if snap.fTitle != e.Title {
			ch = append(ch, 1)
		}
		if !slices.Equal(snap.fTags, e.Tags) {
			ch = append(ch, 2)
		}
		if !slices.Equal(snap.fNums, e.Nums) {
			ch = append(ch, 3)
		}
		return ch
	},
	SetPK:   func(e *models.Article, id int64) { e.ID = id },
	PKValue: func(e *models.Article) any { return e.ID },
}
