// Code generated by sorm gen. DO NOT EDIT.

package sormgen

import (
	"time"

	"github.com/dvislobokov/sorm"

	models "github.com/dvislobokov/sorm/examples/blog/models"
)

// Article holds typed column descriptors for models.Article.
var Article = struct {
	ID          sorm.OrdCol[models.Article, int64]
	AuthorID    sorm.OrdCol[models.Article, int64]
	Title       sorm.StrCol[models.Article]
	Views       sorm.OrdCol[models.Article, int]
	PublishedAt sorm.OrdCol[models.Article, time.Time]
	Author      sorm.BelongsTo[models.Article, models.Author]
}{
	ID:          sorm.NewOrdCol[models.Article, int64]("articles", "id"),
	AuthorID:    sorm.NewOrdCol[models.Article, int64]("articles", "author_id"),
	Title:       sorm.NewStrCol[models.Article]("articles", "title"),
	Views:       sorm.NewOrdCol[models.Article, int]("articles", "views"),
	PublishedAt: sorm.NewOrdCol[models.Article, time.Time]("articles", "published_at"),
	Author: sorm.NewBelongsTo[models.Article, models.Author](
		"author_id",
		func(c *models.Article) any { return c.AuthorID },
		func(c *models.Article, p *models.Author) { c.Author = p },
	),
}

type articleSnap struct {
	fAuthorID    int64
	fTitle       string
	fViews       int
	fPublishedAt *time.Time
}

func init() {
	sorm.Register(articleMeta)
	sorm.RegisterTable(articleTableDef)
}

var articleTableDef = sorm.TableDef{
	Name: "articles",
	Columns: []sorm.ColumnDef{
		{Name: "id", GoKind: "int64", PK: true, Auto: true},
		{Name: "author_id", GoKind: "int64", RefTable: "authors", RefCol: "id"},
		{Name: "title", GoKind: "string"},
		{Name: "views", GoKind: "int"},
		{Name: "published_at", GoKind: "time", Nullable: true},
	},
}

var articleMeta = sorm.Meta[models.Article]{
	Table:      "articles",
	PK:         "id",
	Auto:       true,
	SelectCols: []string{"id", "author_id", "title", "views", "published_at"},
	InsertCols: []string{"author_id", "title", "views", "published_at"},
	Scan: func(e *models.Article) []any {
		return []any{&e.ID, &e.AuthorID, &e.Title, &e.Views, &e.PublishedAt}
	},
	InsertValues: func(e *models.Article) []any {
		return []any{e.AuthorID, e.Title, e.Views, e.PublishedAt}
	},
	ValuesFor: func(e *models.Article, cols []int) []any {
		out := make([]any, len(cols))
		for i, c := range cols {
			switch c {
			case 0:
				out[i] = e.ID
			case 1:
				out[i] = e.AuthorID
			case 2:
				out[i] = e.Title
			case 3:
				out[i] = e.Views
			case 4:
				out[i] = e.PublishedAt
			}
		}
		return out
	},
	Snapshot: func(e *models.Article) any {
		return articleSnap{
			fAuthorID:    e.AuthorID,
			fTitle:       e.Title,
			fViews:       e.Views,
			fPublishedAt: sorm.CloneTimePtr(e.PublishedAt),
		}
	},
	Diff: func(s any, e *models.Article) []int {
		snap := s.(articleSnap)
		var ch []int
		if snap.fAuthorID != e.AuthorID {
			ch = append(ch, 1)
		}
		if snap.fTitle != e.Title {
			ch = append(ch, 2)
		}
		if snap.fViews != e.Views {
			ch = append(ch, 3)
		}
		if !sorm.TimePtrEq(snap.fPublishedAt, e.PublishedAt) {
			ch = append(ch, 4)
		}
		return ch
	},
	SetPK:   func(e *models.Article, id int64) { e.ID = id },
	PKValue: func(e *models.Article) any { return e.ID },
	Refs: []sorm.Ref[models.Article]{
		{
			FKCol:   "author_id",
			NotNull: true,
			Nav: func(e *models.Article) any {
				if e.Author == nil {
					return nil
				}
				return e.Author
			},
			NavPK:    func(e *models.Article) any { return e.Author.ID },
			SetFK:    func(e *models.Article, pk any) { e.AuthorID = pk.(int64) },
			FKIsZero: func(e *models.Article) bool { return e.AuthorID == 0 },
		},
	},
	RefTables: []string{"authors"},
}
