// Code generated by sorm gen. DO NOT EDIT.

package sormgen

import (
	"time"

	"sorm"

	models "sorm/examples/blog/models"
)

// Article — типизированные дескрипторы колонок models.Article.
var Article = struct {
	ID          sorm.OrdCol[models.Article, int64]
	AuthorID    sorm.OrdCol[models.Article, int64]
	Title       sorm.StrCol[models.Article]
	Views       sorm.OrdCol[models.Article, int]
	PublishedAt sorm.OrdCol[models.Article, time.Time]
}{
	ID:          sorm.NewOrdCol[models.Article, int64]("id"),
	AuthorID:    sorm.NewOrdCol[models.Article, int64]("author_id"),
	Title:       sorm.NewStrCol[models.Article]("title"),
	Views:       sorm.NewOrdCol[models.Article, int]("views"),
	PublishedAt: sorm.NewOrdCol[models.Article, time.Time]("published_at"),
}

type articleSnap struct {
	fAuthorID    int64
	fTitle       string
	fViews       int
	fPublishedAt *time.Time
}

func init() { sorm.Register(articleMeta) }

var articleMeta = sorm.Meta[models.Article]{
	Table:      "articles",
	PK:         "id",
	Auto:       true,
	SelectCols: []string{"id", "author_id", "title", "views", "published_at"},
	InsertCols: []string{"author_id", "title", "views", "published_at"},
	Scan: func(e *models.Article) []any {
		return []any{&e.ID, &e.AuthorID, &e.Title, &e.Views, &e.PublishedAt}
	},
	InsertValues: func(e *models.Article) []any {
		return []any{e.AuthorID, e.Title, e.Views, e.PublishedAt}
	},
	ValuesFor: func(e *models.Article, cols []int) []any {
		out := make([]any, len(cols))
		for i, c := range cols {
			switch c {
			case 0:
				out[i] = e.ID
			case 1:
				out[i] = e.AuthorID
			case 2:
				out[i] = e.Title
			case 3:
				out[i] = e.Views
			case 4:
				out[i] = e.PublishedAt
			}
		}
		return out
	},
	Snapshot: func(e *models.Article) any {
		return articleSnap{
			fAuthorID:    e.AuthorID,
			fTitle:       e.Title,
			fViews:       e.Views,
			fPublishedAt: sorm.CloneTimePtr(e.PublishedAt),
		}
	},
	Diff: func(s any, e *models.Article) []int {
		snap := s.(articleSnap)
		var ch []int
		if snap.fAuthorID != e.AuthorID {
			ch = append(ch, 1)
		}
		if snap.fTitle != e.Title {
			ch = append(ch, 2)
		}
		if snap.fViews != e.Views {
			ch = append(ch, 3)
		}
		if !sorm.TimePtrEq(snap.fPublishedAt, e.PublishedAt) {
			ch = append(ch, 4)
		}
		return ch
	},
	SetPK: func(e *models.Article, id int64) { e.ID = id },
}
