// Code generated by sorm gen. DO NOT EDIT.

package sormgen

import (
	"time"

	"sorm"

	models "sorm/examples/blog/models"
)

// Author — типизированные дескрипторы колонок models.Author.
var Author = struct {
	ID       sorm.OrdCol[models.Author, int64]
	Name     sorm.StrCol[models.Author]
	Email    sorm.StrCol[models.Author]
	Active   sorm.Col[models.Author, bool]
	Rating   sorm.OrdCol[models.Author, float64]
	JoinedAt sorm.OrdCol[models.Author, time.Time]
	Version  sorm.OrdCol[models.Author, int64]
	Articles sorm.HasMany[models.Author, models.Article]
}{
	ID:       sorm.NewOrdCol[models.Author, int64]("authors", "id"),
	Name:     sorm.NewStrCol[models.Author]("authors", "name"),
	Email:    sorm.NewStrCol[models.Author]("authors", "email"),
	Active:   sorm.NewCol[models.Author, bool]("authors", "active"),
	Rating:   sorm.NewOrdCol[models.Author, float64]("authors", "rating"),
	JoinedAt: sorm.NewOrdCol[models.Author, time.Time]("authors", "joined_at"),
	Version:  sorm.NewOrdCol[models.Author, int64]("authors", "version"),
	Articles: sorm.NewHasMany[models.Author, models.Article](
		"author_id",
		func(e *models.Author) any { return e.ID },
		func(c *models.Article) any { return c.AuthorID },
		func(e *models.Author) { e.Articles = []*models.Article{} },
		func(e *models.Author, c *models.Article) { e.Articles = append(e.Articles, c) },
	),
}

type authorSnap struct {
	fName     string
	fEmail    string
	fActive   bool
	fRating   float64
	fJoinedAt time.Time
}

func init() {
	sorm.Register(authorMeta)
	sorm.RegisterTable(authorTableDef)
}

var authorTableDef = sorm.TableDef{
	Name: "authors",
	Columns: []sorm.ColumnDef{
		{Name: "id", GoKind: "int64", PK: true, Auto: true},
		{Name: "name", GoKind: "string"},
		{Name: "email", GoKind: "string", Unique: true},
		{Name: "active", GoKind: "bool"},
		{Name: "rating", GoKind: "float64"},
		{Name: "joined_at", GoKind: "time"},
		{Name: "version", GoKind: "int64"},
	},
}

var authorMeta = sorm.Meta[models.Author]{
	Table:      "authors",
	PK:         "id",
	Auto:       true,
	VersionCol: "version",
	SelectCols: []string{"id", "name", "email", "active", "rating", "joined_at", "version"},
	InsertCols: []string{"name", "email", "active", "rating", "joined_at", "version"},
	Scan: func(e *models.Author) []any {
		return []any{&e.ID, &e.Name, &e.Email, &e.Active, &e.Rating, &e.JoinedAt, &e.Version}
	},
	InsertValues: func(e *models.Author) []any {
		return []any{e.Name, e.Email, e.Active, e.Rating, e.JoinedAt, e.Version}
	},
	ValuesFor: func(e *models.Author, cols []int) []any {
		out := make([]any, len(cols))
		for i, c := range cols {
			switch c {
			case 0:
				out[i] = e.ID
			case 1:
				out[i] = e.Name
			case 2:
				out[i] = e.Email
			case 3:
				out[i] = e.Active
			case 4:
				out[i] = e.Rating
			case 5:
				out[i] = e.JoinedAt
			case 6:
				out[i] = e.Version
			}
		}
		return out
	},
	Snapshot: func(e *models.Author) any {
		return authorSnap{
			fName:     e.Name,
			fEmail:    e.Email,
			fActive:   e.Active,
			fRating:   e.Rating,
			fJoinedAt: e.JoinedAt.Round(0),
		}
	},
	Diff: func(s any, e *models.Author) []int {
		snap := s.(authorSnap)
		var ch []int
		if snap.fName != e.Name {
			ch = append(ch, 1)
		}
		if snap.fEmail != e.Email {
			ch = append(ch, 2)
		}
		if snap.fActive != e.Active {
			ch = append(ch, 3)
		}
		if snap.fRating != e.Rating {
			ch = append(ch, 4)
		}
		if !snap.fJoinedAt.Equal(e.JoinedAt) {
			ch = append(ch, 5)
		}
		return ch
	},
	SetPK:      func(e *models.Author, id int64) { e.ID = id },
	PKValue:    func(e *models.Author) any { return e.ID },
	GetVersion: func(e *models.Author) int64 { return e.Version },
	SetVersion: func(e *models.Author, v int64) { e.Version = v },
}
